-- raiders.lua — Humanoid raider species definitions
-- Faction soldiers, outlaws, scavengers, and precursor survivors.
-- These are spawned as creatures with humanoid=true and optional ranged stats.
-- Ranged raiders fire projectiles via Ranged.creatureFire().

local Raiders = {}

---------------------------------------------------------------------------
-- Humanoid raider species (merged into Creatures.SPECIES at load)
---------------------------------------------------------------------------

Raiders.SPECIES = {
    -- Outlaws — independent, appear early, cheap, expendable
    outlaw_thug = {
        name = 'Outlaw Thug', desc = 'Desperate raider. Fights with scrap weapons.',
        tier = 'raider',
        health = 50, speed = 3, damage = 10,
        thermalCore = 2, meat = 0,
        hostile = true, aggroRange = 10, leashRange = 999,
        color = { 0.6, 0.45, 0.3 },
        size = 0.7,
        humanoid = true,
        loot = { metal = 1 },
    },
    outlaw_brawler = {
        name = 'Outlaw Brawler', desc = 'Hardened fighter. Tougher than the average thug.',
        tier = 'raider',
        health = 80, speed = 3, damage = 16,
        thermalCore = 3, meat = 0,
        hostile = true, aggroRange = 10, leashRange = 999,
        color = { 0.55, 0.4, 0.25 },
        size = 0.8,
        humanoid = true,
        loot = { metal = 2 },
    },
    outlaw_gunner = {
        name = 'Outlaw Gunner', desc = 'Armed with a jury-rigged pistol. Inaccurate but dangerous.',
        tier = 'raider',
        health = 45, speed = 3, damage = 6,
        thermalCore = 3, meat = 0,
        hostile = true, aggroRange = 12, leashRange = 999,
        color = { 0.5, 0.4, 0.3 },
        size = 0.7,
        humanoid = true,
        rangedDamage = 12, rangedRange = 6, rangedAccuracy = 0.45,
        rangedCooldown = 2.0,
        loot = { metal = 1, components = 1 },
    },
    outlaw_marksman = {
        name = 'Outlaw Marksman', desc = 'Scavenged rifle. Patient and lethal at range.',
        tier = 'raider',
        health = 40, speed = 2.5, damage = 6,
        thermalCore = 4, meat = 0,
        hostile = true, aggroRange = 14, leashRange = 999,
        color = { 0.45, 0.35, 0.25 },
        size = 0.7,
        humanoid = true,
        rangedDamage = 22, rangedRange = 10, rangedAccuracy = 0.65,
        rangedCooldown = 2.5,
        loot = { metal = 2, components = 1 },
    },

    -- Scavenger Crews — faction raiders, mid-tier
    scav_militia = {
        name = 'Scav Militia', desc = 'Scavenger foot soldier. Fights for salvage rights.',
        tier = 'raider',
        health = 60, speed = 3, damage = 12,
        thermalCore = 3, meat = 0,
        hostile = true, aggroRange = 10, leashRange = 999,
        color = { 0.5, 0.55, 0.4 },
        size = 0.7,
        humanoid = true,
        loot = { food = 2, wood = 2 },
    },
    scav_scrapper = {
        name = 'Scav Scrapper', desc = 'Armored salvager. Wears scrap plate.',
        tier = 'raider',
        health = 90, speed = 2.5, damage = 18,
        thermalCore = 5, meat = 0,
        hostile = true, aggroRange = 10, leashRange = 999,
        color = { 0.45, 0.5, 0.35 },
        size = 0.8,
        humanoid = true,
        armorReduction = 4,
        loot = { metal = 3 },
    },
    scav_sharpshooter = {
        name = 'Scav Sharpshooter', desc = 'Scavenger sniper. Covers the crew from range.',
        tier = 'raider',
        health = 50, speed = 2.5, damage = 6,
        thermalCore = 4, meat = 0,
        hostile = true, aggroRange = 12, leashRange = 999,
        color = { 0.4, 0.5, 0.35 },
        size = 0.7,
        humanoid = true,
        rangedDamage = 16, rangedRange = 8, rangedAccuracy = 0.60,
        rangedCooldown = 2.0,
        loot = { metal = 1, components = 1 },
    },

    -- Mammona Logistics — corporate enforcers, well-equipped
    mammona_enforcer = {
        name = 'Mammona Enforcer', desc = 'Corporate soldier. Standard-issue sidearm.',
        tier = 'raider',
        health = 70, speed = 3, damage = 8,
        thermalCore = 5, meat = 0,
        hostile = true, aggroRange = 12, leashRange = 999,
        color = { 0.3, 0.35, 0.5 },
        size = 0.7,
        humanoid = true,
        rangedDamage = 14, rangedRange = 7, rangedAccuracy = 0.60,
        rangedCooldown = 1.8,
        loot = { fuel = 2, components = 1 },
    },
    mammona_heavy = {
        name = 'Mammona Heavy', desc = 'Heavy trooper. Battle rifle and plate armor.',
        tier = 'raider',
        health = 100, speed = 2.5, damage = 12,
        thermalCore = 8, meat = 0,
        hostile = true, aggroRange = 12, leashRange = 999,
        color = { 0.25, 0.3, 0.5 },
        size = 0.85,
        humanoid = true,
        armorReduction = 6,
        rangedDamage = 22, rangedRange = 9, rangedAccuracy = 0.65,
        rangedCooldown = 2.0,
        loot = { fuel = 3, metal = 2, components = 1 },
    },

    -- MasTema Incorporated — black ops, elite fighters
    mastema_operative = {
        name = 'MasTema Operative', desc = 'Corporate wetwork agent. Precise and lethal.',
        tier = 'raider',
        health = 80, speed = 3.5, damage = 14,
        thermalCore = 6, meat = 0,
        hostile = true, aggroRange = 14, leashRange = 999,
        color = { 0.2, 0.2, 0.25 },
        size = 0.7,
        humanoid = true,
        rangedDamage = 18, rangedRange = 8, rangedAccuracy = 0.70,
        rangedCooldown = 1.5,
        loot = { components = 2, metal = 1 },
    },
    mastema_sniper = {
        name = 'MasTema Sniper', desc = 'Long-range assassin. One shot, one kill.',
        tier = 'raider',
        health = 50, speed = 2.5, damage = 8,
        thermalCore = 8, meat = 0,
        hostile = true, aggroRange = 16, leashRange = 999,
        color = { 0.15, 0.15, 0.2 },
        size = 0.7,
        humanoid = true,
        rangedDamage = 30, rangedRange = 12, rangedAccuracy = 0.80,
        rangedCooldown = 3.0,
        loot = { components = 3 },
    },
    mastema_breacher = {
        name = 'MasTema Breacher', desc = 'Demolitions expert. Smashes through walls.',
        tier = 'raider',
        health = 120, speed = 2.5, damage = 25,
        thermalCore = 6, meat = 0,
        hostile = true, aggroRange = 10, leashRange = 999,
        color = { 0.25, 0.2, 0.15 },
        size = 0.9,
        humanoid = true,
        breacher = true,
        armorReduction = 5,
        loot = { metal = 3, components = 1 },
    },

    -- Black Maw — pirates, aggressive, mid-tier bruisers
    maw_raider = {
        name = 'Maw Raider', desc = 'Black Maw pirate. Armed and mean.',
        tier = 'raider',
        health = 65, speed = 3, damage = 14,
        thermalCore = 3, meat = 0,
        hostile = true, aggroRange = 10, leashRange = 999,
        color = { 0.35, 0.2, 0.2 },
        size = 0.75,
        humanoid = true,
        loot = { metal = 2, fuel = 1 },
    },
    maw_breacher = {
        name = 'Maw Breacher', desc = 'Demolitions pirate. Smashes entry points.',
        tier = 'raider',
        health = 110, speed = 2.5, damage = 22,
        thermalCore = 5, meat = 0,
        hostile = true, aggroRange = 10, leashRange = 999,
        color = { 0.4, 0.2, 0.15 },
        size = 0.85,
        humanoid = true,
        breacher = true,
        armorReduction = 5,
        loot = { metal = 3, components = 1 },
    },
    maw_heavy = {
        name = 'Maw Heavy', desc = 'Pirate enforcer. Scrap plate and a big gun.',
        tier = 'raider',
        health = 95, speed = 2.5, damage = 10,
        thermalCore = 6, meat = 0,
        hostile = true, aggroRange = 12, leashRange = 999,
        color = { 0.3, 0.15, 0.15 },
        size = 0.85,
        humanoid = true,
        armorReduction = 6,
        rangedDamage = 18, rangedRange = 8, rangedAccuracy = 0.55,
        rangedCooldown = 2.0,
        loot = { metal = 3, fuel = 2 },
    },

    -- Void Serpents — intel operatives, fast and sneaky
    serpent_infiltrator = {
        name = 'Serpent Infiltrator', desc = 'Void Serpent agent. Fast, quiet, suppressed pistol.',
        tier = 'raider',
        health = 55, speed = 4, damage = 12,
        thermalCore = 4, meat = 0,
        hostile = true, aggroRange = 14, leashRange = 999,
        color = { 0.2, 0.25, 0.3 },
        size = 0.65,
        humanoid = true,
        rangedDamage = 14, rangedRange = 7, rangedAccuracy = 0.65,
        rangedCooldown = 1.5,
        loot = { components = 2 },
    },
    serpent_saboteur = {
        name = 'Serpent Saboteur', desc = 'Void Serpent demo specialist. Targets infrastructure.',
        tier = 'raider',
        health = 60, speed = 3.5, damage = 18,
        thermalCore = 5, meat = 0,
        hostile = true, aggroRange = 12, leashRange = 999,
        color = { 0.15, 0.2, 0.3 },
        size = 0.7,
        humanoid = true,
        breacher = true,
        loot = { components = 3 },
    },

    -- Rust Reavers — scrap-armored brawlers, melee-heavy
    reaver_scrapper = {
        name = 'Reaver Scrapper', desc = 'Rust Reaver foot soldier. Scrap armor, cutting torch.',
        tier = 'raider',
        health = 75, speed = 3, damage = 16,
        thermalCore = 3, meat = 0,
        hostile = true, aggroRange = 10, leashRange = 999,
        color = { 0.5, 0.35, 0.2 },
        size = 0.75,
        humanoid = true,
        armorReduction = 4,
        loot = { metal = 3, wood = 1 },
    },
    reaver_welder = {
        name = 'Reaver Welder', desc = 'Heavy Reaver. Welding rig repurposed as a weapon.',
        tier = 'raider',
        health = 100, speed = 2.5, damage = 24,
        thermalCore = 5, meat = 0,
        hostile = true, aggroRange = 10, leashRange = 999,
        color = { 0.55, 0.35, 0.15 },
        size = 0.85,
        humanoid = true,
        armorReduction = 5,
        breacher = true,
        loot = { metal = 4, components = 1 },
    },

    -- Zenith Syndicate — organized crime, well-equipped
    zenith_thug = {
        name = 'Zenith Thug', desc = 'Syndicate muscle. Club and a bad attitude.',
        tier = 'raider',
        health = 60, speed = 3, damage = 14,
        thermalCore = 3, meat = 0,
        hostile = true, aggroRange = 10, leashRange = 999,
        color = { 0.4, 0.3, 0.45 },
        size = 0.75,
        humanoid = true,
        loot = { food = 2, fuel = 1 },
    },
    zenith_gunner = {
        name = 'Zenith Gunner', desc = 'Syndicate ranged fighter. Stolen Mammona hardware.',
        tier = 'raider',
        health = 55, speed = 3, damage = 8,
        thermalCore = 5, meat = 0,
        hostile = true, aggroRange = 12, leashRange = 999,
        color = { 0.35, 0.25, 0.45 },
        size = 0.7,
        humanoid = true,
        rangedDamage = 16, rangedRange = 8, rangedAccuracy = 0.60,
        rangedCooldown = 1.8,
        loot = { components = 2 },
    },
    zenith_enforcer = {
        name = 'Zenith Enforcer', desc = 'Syndicate elite. Armored, armed, and paid well.',
        tier = 'raider',
        health = 90, speed = 3, damage = 12,
        thermalCore = 7, meat = 0,
        hostile = true, aggroRange = 14, leashRange = 999,
        color = { 0.3, 0.2, 0.45 },
        size = 0.8,
        humanoid = true,
        armorReduction = 6,
        rangedDamage = 20, rangedRange = 9, rangedAccuracy = 0.65,
        rangedCooldown = 2.0,
        loot = { components = 2, metal = 2 },
    },

    -- Sons of the Pale Moon — cult zealots, fanatical melee with ranged support
    pale_moon_zealot = {
        name = 'Pale Moon Zealot', desc = 'Cult fighter. Crescent-scarred, fights to the last.',
        tier = 'raider',
        health = 70, speed = 3.5, damage = 18,
        thermalCore = 4, meat = 0,
        hostile = true, aggroRange = 12, leashRange = 999,
        color = { 0.7, 0.7, 0.75 },
        size = 0.75,
        humanoid = true,
        loot = { components = 1 },
    },
    pale_moon_priest = {
        name = 'Pale Moon Priest', desc = 'Cult leader. Thermal lance and a bad sermon.',
        tier = 'raider',
        health = 60, speed = 3, damage = 10,
        thermalCore = 6, meat = 0,
        hostile = true, aggroRange = 14, leashRange = 999,
        color = { 0.75, 0.75, 0.8 },
        size = 0.7,
        humanoid = true,
        rangedDamage = 22, rangedRange = 9, rangedAccuracy = 0.60,
        rangedCooldown = 2.5,
        loot = { components = 1, circuit = 1 },
    },

    -- Precursor survivors — ancient, powerful, late-game
    precursor_scout = {
        name = 'Precursor Scout', desc = 'Ancient survivor. Energy sidearm, fast recon.',
        tier = 'raider',
        health = 90, speed = 4, damage = 10,
        thermalCore = 8, meat = 0,
        hostile = true, aggroRange = 14, leashRange = 999,
        color = { 0.6, 0.7, 0.8 },
        size = 0.7,
        humanoid = true,
        rangedDamage = 20, rangedRange = 8, rangedAccuracy = 0.70,
        rangedCooldown = 1.5,
        loot = { components = 2, circuit = 1 },
    },
    precursor_warrior = {
        name = 'Precursor Warrior', desc = 'Armored survivor. Energy blade, hard to kill.',
        tier = 'raider',
        health = 150, speed = 3, damage = 30,
        thermalCore = 10, meat = 0,
        hostile = true, aggroRange = 12, leashRange = 999,
        color = { 0.5, 0.6, 0.75 },
        size = 0.85,
        humanoid = true,
        armorReduction = 8,
        loot = { components = 3, circuit = 1 },
    },
    precursor_sage = {
        name = 'Precursor Sage', desc = 'Ancient elder. Long-range energy lance. Devastating.',
        tier = 'raider',
        health = 70, speed = 2, damage = 8,
        thermalCore = 12, meat = 0,
        hostile = true, aggroRange = 16, leashRange = 999,
        color = { 0.7, 0.75, 0.9 },
        size = 0.75,
        humanoid = true,
        rangedDamage = 35, rangedRange = 11, rangedAccuracy = 0.75,
        rangedCooldown = 3.5,
        loot = { components = 3, circuit = 2 },
    },
    erebus_latent = {
        name = 'Erebus-Touched', desc = 'Still shaped like a survivor. Moves like something listening to a second set of orders.',
        tier = 'raider',
        health = 65, speed = 3.2, damage = 14,
        thermalCore = 0, meat = 0,
        hostile = true, aggroRange = 12, leashRange = 999,
        color = { 0.62, 0.66, 0.78 },
        size = 0.72,
        humanoid = true,
        loot = { eldritch_ichor = 1 },
    },
    erebus_thrall = {
        name = 'Erebus Thrall', desc = 'A contaminated miner or scout driven back toward the signal below.',
        tier = 'raider',
        health = 90, speed = 3.0, damage = 20,
        thermalCore = 0, meat = 0,
        hostile = true, aggroRange = 14, leashRange = 999,
        color = { 0.45, 0.5, 0.58 },
        size = 0.8,
        humanoid = true,
        armorReduction = 3,
        loot = { eldritch_ichor = 2, chitin_plate = 1 },
    },
    erebus_vessel = {
        name = 'Vessel Host', desc = 'The person is still present. The thing inside is more interested in you.',
        tier = 'raider',
        health = 115, speed = 2.7, damage = 26,
        thermalCore = 0, meat = 0,
        hostile = true, aggroRange = 14, leashRange = 999,
        color = { 0.58, 0.42, 0.46 },
        size = 0.88,
        humanoid = true,
        armorReduction = 4,
        breacher = true,
        loot = { eldritch_ichor = 3, void_crystal = 1 },
    },
    erebus_herald = {
        name = 'Whisper Herald', desc = 'A prophet-shell broadcasting instructions no human voice should be able to hold.',
        tier = 'raider',
        health = 105, speed = 2.8, damage = 12,
        thermalCore = 0, meat = 0,
        hostile = true, aggroRange = 16, leashRange = 999,
        color = { 0.75, 0.67, 0.86 },
        size = 0.8,
        humanoid = true,
        rangedDamage = 24, rangedRange = 9, rangedAccuracy = 0.68,
        rangedCooldown = 2.3,
        loot = { eldritch_ichor = 2, void_crystal = 1, caustic_liquid = 1 },
    },
}

---------------------------------------------------------------------------
-- Raid cost table for humanoid raiders (used by raids.lua budget system)
---------------------------------------------------------------------------

Raiders.COST = {
    outlaw_thug      = 6,
    outlaw_brawler   = 12,
    outlaw_gunner    = 10,
    outlaw_marksman  = 18,
    scav_militia     = 8,
    scav_scrapper    = 14,
    scav_sharpshooter = 15,
    mammona_enforcer = 15,
    mammona_heavy    = 25,
    mastema_operative = 22,
    mastema_sniper   = 28,
    mastema_breacher = 20,
    precursor_scout  = 20,
    precursor_warrior = 25,
    precursor_sage   = 35,
    -- Black Maw
    maw_raider       = 10,
    maw_breacher     = 18,
    maw_heavy        = 20,
    -- Void Serpents
    serpent_infiltrator = 16,
    serpent_saboteur  = 20,
    -- Rust Reavers
    reaver_scrapper  = 12,
    reaver_welder    = 18,
    -- Zenith Syndicate
    zenith_thug      = 8,
    zenith_gunner    = 14,
    zenith_enforcer  = 22,
    -- Sons of the Pale Moon
    pale_moon_zealot = 12,
    pale_moon_priest = 20,
    -- Erebus-Touched
    erebus_latent    = 14,
    erebus_thrall    = 20,
    erebus_vessel    = 28,
    erebus_herald    = 34,
}

---------------------------------------------------------------------------
-- Merge raider species into main SPECIES table
---------------------------------------------------------------------------

function Raiders.register()
    local ok, Creatures = pcall(require, 'src.creatures.creatures')
    if ok and Creatures.SPECIES then
        for id, def in pairs(Raiders.SPECIES) do
            Creatures.SPECIES[id] = def
        end
    end
end

return Raiders
