-- species_defs.lua — Creature species data definitions
-- Pure data, no requires. Returned as a table, consumed by creatures.lua.
-- raiders.lua mutates this table at startup to add humanoid raider species.

return {
    -- Small fauna (passive, flee from colonists)
    frost_hare = {
        name = 'Frost Hare', desc = 'Small, fast. Flees on sight.',
        tier = 'small',
        health = 15, speed = 5, damage = 0,
        thermalCore = 1, meat = 2,
        hostile = false, fleeRange = 8,
        color = { 0.8, 0.85, 0.9 },
        size = 0.4,
    },
    ice_fox = {
        name = 'Ice Fox', desc = 'Skittish predator. Will bite if cornered.',
        tier = 'small',
        health = 25, speed = 4, damage = 3,
        thermalCore = 2, meat = 3,
        hostile = false, fleeRange = 6,
        color = { 0.7, 0.75, 0.85 },
        size = 0.5,
    },
    snow_grouse = {
        name = 'Snow Grouse', desc = 'Plump ground bird. Easy prey.',
        tier = 'small',
        health = 10, speed = 6, damage = 0,
        thermalCore = 1, meat = 1,
        hostile = false, fleeRange = 10,
        color = { 0.85, 0.8, 0.75 },
        size = 0.3,
    },

    -- Medium fauna (territorial, attack if approached)
    tundra_wolf = {
        name = 'Tundra Wolf', desc = 'Pack hunter. Dangerous in numbers.',
        tier = 'medium',
        health = 60, speed = 4, damage = 12,
        thermalCore = 5, meat = 6,
        hostile = true, aggroRange = 10, leashRange = 20,
        packSize = { 2, 5 },
        color = { 0.5, 0.5, 0.55 },
        size = 0.7,
    },
    glacier_bear = {
        name = 'Glacier Bear', desc = 'Slow but tough. Hits hard.',
        tier = 'medium',
        health = 120, speed = 2.5, damage = 25,
        thermalCore = 10, meat = 15,
        hostile = true, aggroRange = 7, leashRange = 15,
        color = { 0.6, 0.55, 0.5 },
        size = 0.9,
    },
    ice_stalker = {
        name = 'Ice Stalker', desc = 'Ambush predator. Patrols wide territory.',
        tier = 'medium',
        health = 80, speed = 3.5, damage = 18,
        thermalCore = 8, meat = 8,
        hostile = true, aggroRange = 12, leashRange = 25,
        color = { 0.4, 0.5, 0.6 },
        size = 0.8,
    },

    -- Medium-large fauna
    ice_brute = {
        name = 'Ice Brute', desc = 'Hulking brute. Will smash through walls.',
        tier = 'medium',
        health = 200, speed = 2, damage = 35,
        thermalCore = 15, meat = 20,
        hostile = true, aggroRange = 12, leashRange = 25,
        color = { 0.45, 0.5, 0.65 },
        size = 1.5,
        breacher = true,
    },
    snow_ape = {
        name = 'Snow Ape', desc = 'Knuckle-drags through drifts. Territorial and mean.',
        tier = 'medium',
        health = 150, speed = 3, damage = 22,
        thermalCore = 12, meat = 15,
        hostile = true, aggroRange = 8, leashRange = 20,
        color = { 0.75, 0.78, 0.82 },
        size = 1.3,
    },
    stalker = {
        name = 'Stalker', desc = 'Fast, silent, hunts at night. Fear aura drains morale.',
        tier = 'medium',
        health = 100, speed = 5, damage = 28,
        thermalCore = 10, meat = 5,
        hostile = true, aggroRange = 15, leashRange = 30,
        color = { 0.25, 0.2, 0.15 },
        size = 1.1,
        nightHunter = true,
        fearAura = 6,
    },
    shade = {
        name = 'Shade', desc = 'Translucent predator. No meat yield.',
        tier = 'medium',
        health = 70, speed = 4.5, damage = 15,
        thermalCore = 8, meat = 0,
        hostile = true, aggroRange = 14, leashRange = 25,
        color = { 0.6, 0.7, 0.9 },
        size = 0.9,
    },
    dire_wolf = {
        name = 'Dire Wolf', desc = 'Larger than tundra wolves. Hunts in bigger packs.',
        tier = 'medium',
        health = 90, speed = 4.5, damage = 18,
        thermalCore = 7, meat = 10,
        hostile = true, aggroRange = 12, leashRange = 22,
        packSize = { 3, 6 },
        color = { 0.35, 0.35, 0.4 },
        size = 0.85,
    },
    mammoth = {
        name = 'Tusk Grazer', desc = 'Massive and passive unless provoked. Do not corner it.',
        tier = 'medium',
        health = 250, speed = 1.8, damage = 30,
        thermalCore = 18, meat = 30,
        hostile = false, fleeRange = 0,
        aggroRange = 5, leashRange = 15,
        color = { 0.5, 0.4, 0.35 },
        size = 1.6,
    },
    sabertooth = {
        name = 'Permafrost Fang', desc = 'Ambush predator. Bites through cold-gear like paper.',
        tier = 'medium',
        health = 110, speed = 5, damage = 24,
        thermalCore = 9, meat = 8,
        hostile = true, aggroRange = 10, leashRange = 20,
        color = { 0.6, 0.5, 0.35 },
        size = 0.9,
    },

    -- Megafauna (boss creatures)
    frost_titan = {
        name = 'Frost Titan', desc = 'Towering ice creature. Worth the ammunition.',
        tier = 'megafauna',
        health = 500, speed = 1.5, damage = 50,
        thermalCore = 50, meat = 40,
        hostile = true, aggroRange = 15, leashRange = 30,
        color = { 0.3, 0.35, 0.5 },
        size = 2.0,
    },
    thermal_wurm = {
        name = 'Thermal Wurm', desc = 'Burrowing heat predator. Drawn to generators.',
        tier = 'megafauna',
        health = 400, speed = 2, damage = 40,
        thermalCore = 80, meat = 25,
        hostile = true, aggroRange = 12, leashRange = 25,
        color = { 0.7, 0.3, 0.2 },
        size = 1.8,
    },
    glacial_leviathan = {
        name = 'Glacial Leviathan', desc = 'Largest natural creature on Erebus. Shakes the ground when it walks.',
        tier = 'megafauna',
        health = 800, speed = 1, damage = 70,
        thermalCore = 120, meat = 60,
        hostile = true, aggroRange = 20, leashRange = 40,
        color = { 0.2, 0.25, 0.45 },
        size = 2.5,
    },
    ancient_brute = {
        name = 'Ancient Brute', desc = 'Old-growth ice brute. Will come through the walls.',
        tier = 'megafauna',
        health = 600, speed = 1.5, damage = 55,
        thermalCore = 60, meat = 50,
        hostile = true, aggroRange = 18, leashRange = 35,
        color = { 0.4, 0.35, 0.3 },
        size = 2.2,
        breacher = true,
    },
    alpha_stalker = {
        name = 'Alpha Stalker', desc = 'Pack leader. Never stops chasing. Fear aura.',
        tier = 'megafauna',
        health = 350, speed = 4, damage = 45,
        thermalCore = 40, meat = 10,
        hostile = true, aggroRange = 20, leashRange = 999,
        color = { 0.15, 0.1, 0.1 },
        size = 1.6,
        nightHunter = true,
        fearAura = 10,
    },
    mountain_titan = {
        name = 'Mountain Titan', desc = 'Living mountain. Breaks everything it touches.',
        tier = 'megafauna',
        health = 1000, speed = 0.8, damage = 80,
        thermalCore = 100, meat = 70,
        hostile = true, aggroRange = 15, leashRange = 40,
        color = { 0.35, 0.3, 0.25 },
        size = 3.0,
        breacher = true,
    },
    ice_colossus = {
        name = 'Ice Colossus', desc = 'Animated ice formation. Cracks apart and reforms.',
        tier = 'megafauna',
        health = 700, speed = 0.7, damage = 60,
        thermalCore = 80, meat = 0,
        hostile = true, aggroRange = 12, leashRange = 30,
        color = { 0.5, 0.6, 0.8 },
        size = 2.8,
    },
    storm_titan = {
        name = 'Storm Titan', desc = 'Charges through storms. Fast for its size.',
        tier = 'megafauna',
        health = 550, speed = 1.8, damage = 50,
        thermalCore = 55, meat = 40,
        hostile = true, aggroRange = 16, leashRange = 35,
        color = { 0.3, 0.4, 0.6 },
        size = 2.3,
    },

    -- Eldritch horrors
    the_hungering = {
        name = 'The Hungering', desc = 'Consumes everything in its path. Does not stop.',
        tier = 'eldritch',
        health = 2000, speed = 1.2, damage = 100,
        thermalCore = 200, meat = 0,
        hostile = true, aggroRange = 25, leashRange = 999,
        color = { 0.1, 0.05, 0.05 },
        size = 4.0,
        breacher = true,
        fearAura = 15,
        nightHunter = true,
    },
    the_pale_thing = {
        name = 'The Pale Thing', desc = 'Looking at it makes your hands shake. High fear aura.',
        tier = 'eldritch',
        health = 1500, speed = 2, damage = 80,
        thermalCore = 150, meat = 0,
        hostile = true, aggroRange = 30, leashRange = 999,
        color = { 0.9, 0.85, 0.8 },
        size = 3.5,
        fearAura = 20,
    },
    that_which_sleeps = {
        name = 'That Which Sleeps', desc = 'Oldest thing on Erebus. Should have stayed buried.',
        tier = 'eldritch',
        health = 3000, speed = 0.5, damage = 120,
        thermalCore = 300, meat = 100,
        hostile = true, aggroRange = 20, leashRange = 999,
        color = { 0.2, 0.3, 0.5 },
        size = 5.0,
        breacher = true,
    },
    fleshwalker = {
        name = 'Fleshwalker', desc = 'Fast, hunts at night. Nothing left when it feeds.',
        tier = 'eldritch',
        health = 1200, speed = 5, damage = 70,
        thermalCore = 180, meat = 0,
        hostile = true, aggroRange = 25, leashRange = 999,
        color = { 0.0, 0.0, 0.05 },
        size = 2.5,
        nightHunter = true,
        fearAura = 18,
    },

    -- Eldritch livestock
    gore_shoat = {
        name = 'Gore Shoat', tier = 'eldritch_livestock',
        health = 35, speed = 3, damage = 4,
        thermalCore = 2, meat = 8,
        hostile = false, fleeRange = 3,
        color = { 0.6, 0.15, 0.1 },
        size = 0.4,
        eldritchType = 'flesh',
        desc = 'Piglet with extra eyes. Roots in filth. Grows into a flesh node.',
    },
    weeping_calf = {
        name = 'Weeping Calf', tier = 'eldritch_livestock',
        health = 30, speed = 1.5, damage = 2,
        thermalCore = 2, meat = 4,
        hostile = false, fleeRange = 2,
        color = { 0.2, 0.05, 0.3 },
        size = 0.5,
        eldritchType = 'ichor',
        desc = 'Leaks dark fluid from birth. Develops ichor sacs as it matures.',
    },
    husk_pup = {
        name = 'Husk Pup', tier = 'eldritch_livestock',
        health = 40, speed = 4, damage = 6,
        thermalCore = 3, meat = 3,
        hostile = false, fleeRange = 6,
        color = { 0.4, 0.35, 0.25 },
        size = 0.35,
        eldritchType = 'chitin',
        desc = 'Follows colonists like a loyal hound. Then the chitin starts growing.',
    },
    void_minnow = {
        name = 'Void Calf', tier = 'eldritch_livestock',
        health = 25, speed = 1, damage = 4,
        thermalCore = 8, meat = 5,
        hostile = false, fleeRange = 4,
        color = { 0.05, 0.0, 0.1 },
        size = 0.2,
        eldritchType = 'void',
        fearAura = 2,
        desc = 'Born the size of a fist. Feeds on corpses and never stops growing.',
    },
    pit_wyrm = {
        name = 'Pit Wyrm', tier = 'eldritch_livestock',
        health = 20, speed = 3, damage = 5,
        thermalCore = 3, meat = 2,
        hostile = false, fleeRange = 5,
        color = { 0.3, 0.1, 0.15 },
        size = 0.2,
        eldritchType = 'serpent',
        desc = 'Finger-length worm. Gets much bigger with feeding.',
    },
    bile_mold = {
        name = 'Bile Mold', desc = 'Yellow-green tissue mass. Grows into a bile sac.',
        tier = 'eldritch_livestock',
        health = 20, speed = 1, damage = 2,
        thermalCore = 1, meat = 3,
        hostile = false, fleeRange = 3,
        color = { 0.3, 0.4, 0.05 },
        size = 0.25,
        eldritchType = 'bile',
    },
    thorn_polyp = {
        name = 'Thorn Polyp', desc = 'Barbed sessile growth. Produces chitin when mature.',
        tier = 'eldritch_livestock',
        health = 40, speed = 1, damage = 5,
        thermalCore = 1, meat = 3,
        hostile = false, fleeRange = 3,
        color = { 0.35, 0.25, 0.2 },
        size = 0.3,
        eldritchType = 'thorn',
    },
    nerve_cluster = {
        name = 'Nerve Cluster', desc = 'Exposed neural tissue. Feeds on corpses.',
        tier = 'eldritch_livestock',
        health = 25, speed = 2, damage = 4,
        thermalCore = 2, meat = 2,
        hostile = false, fleeRange = 5,
        color = { 0.15, 0.05, 0.2 },
        size = 0.2,
        eldritchType = 'nerve',
    },
    rot_bloom = {
        name = 'Rot Bloom', desc = 'Fungal mass that spreads slowly. Produces raw meat.',
        tier = 'eldritch_livestock',
        health = 35, speed = 2, damage = 3,
        thermalCore = 1, meat = 6,
        hostile = false, fleeRange = 3,
        color = { 0.25, 0.15, 0.1 },
        size = 0.3,
        eldritchType = 'rot',
    },

    -- Thermovores
    cinder_mite = {
        name = 'Cinder Mite', desc = 'Cat-sized thermal parasite. Scuttles toward heat sources.',
        tier = 'small',
        health = 12, speed = 5.5, damage = 2,
        thermalCore = 1, meat = 1,
        hostile = false, fleeRange = 7,
        color = { 0.7, 0.4, 0.15 },
        size = 0.3,
    },
    heat_skipper = {
        name = 'Heat Skipper', desc = 'Tiny gliding arthropod. Harmless unless you step on a nest.',
        tier = 'small',
        health = 8, speed = 7, damage = 0,
        thermalCore = 1, meat = 0,
        hostile = false, fleeRange = 12,
        color = { 0.8, 0.5, 0.2 },
        size = 0.2,
    },
    char_hound = {
        name = 'Char Hound', desc = 'Pack predator with mandibles. Circles prey before charging.',
        tier = 'medium',
        health = 75, speed = 4.5, damage = 14,
        thermalCore = 6, meat = 7,
        hostile = true, aggroRange = 11, leashRange = 22,
        packSize = { 2, 4 },
        color = { 0.6, 0.3, 0.1 },
        size = 0.7,
    },
    bore_beetle = {
        name = 'Bore Beetle', desc = 'Armored roller. Curls up and charges through walls.',
        tier = 'medium',
        health = 130, speed = 2.5, damage = 22,
        thermalCore = 10, meat = 12,
        hostile = true, aggroRange = 8, leashRange = 18,
        color = { 0.5, 0.35, 0.15 },
        size = 0.9,
        breacher = true,
    },
    razorjaw = {
        name = 'Razorjaw', desc = 'Mantis predator. Hides under snow, strikes from below.',
        tier = 'medium',
        health = 95, speed = 4, damage = 26,
        thermalCore = 9, meat = 8,
        hostile = true, aggroRange = 12, leashRange = 20,
        color = { 0.55, 0.4, 0.2 },
        size = 0.9,
    },
    spine_lurker = {
        name = 'Spine Lurker', desc = 'Scorpion-type arthropod. Long reach, patrols wide territory.',
        tier = 'medium',
        health = 85, speed = 3.5, damage = 18,
        thermalCore = 7, meat = 6,
        hostile = true, aggroRange = 14, leashRange = 28,
        color = { 0.65, 0.35, 0.1 },
        size = 0.8,
    },
    hive_matron = {
        name = 'Hive Matron', desc = 'Brood queen. Enormous thorax, guards nesting ground.',
        tier = 'megafauna',
        health = 550, speed = 1.2, damage = 45,
        thermalCore = 55, meat = 35,
        hostile = true, aggroRange = 15, leashRange = 30,
        color = { 0.7, 0.25, 0.1 },
        size = 2.0,
    },
    gorge_worm = {
        name = 'Gorge Worm', desc = 'Burrowing predator. Surfaces under prey, drags them down.',
        tier = 'megafauna',
        health = 650, speed = 1.8, damage = 55,
        thermalCore = 70, meat = 40,
        hostile = true, aggroRange = 14, leashRange = 35,
        color = { 0.55, 0.2, 0.1 },
        size = 2.2,
        breacher = true,
    },
    iron_carapace = {
        name = 'Iron Carapace', desc = 'Walking fortress. Exoskeleton deflects small arms fire.',
        tier = 'megafauna',
        health = 900, speed = 0.9, damage = 65,
        thermalCore = 95, meat = 55,
        hostile = true, aggroRange = 12, leashRange = 25,
        color = { 0.4, 0.25, 0.15 },
        size = 2.8,
    },
    the_thermophage = {
        name = 'The Thermophage', desc = 'Apex arthropod. Feeds on reactor heat. Colony-ender.',
        tier = 'eldritch',
        health = 2200, speed = 1.0, damage = 95,
        thermalCore = 220, meat = 0,
        hostile = true, aggroRange = 25, leashRange = 999,
        color = { 0.8, 0.15, 0.0 },
        size = 4.5,
        breacher = true,
        fearAura = 16,
    },

    -- Swarm creatures
    frost_beetle = {
        name = 'Frost Beetle', desc = 'Swarming insect. Weak alone, lethal in numbers.',
        tier = 'swarm',
        health = 20, speed = 5, damage = 5,
        thermalCore = 1, meat = 0,
        hostile = true, aggroRange = 15, leashRange = 999,
        packSize = { 6, 12 },
        color = { 0.4, 0.5, 0.6 },
        size = 0.3,
        noRetreat = true,
    },
    ice_locust = {
        name = 'Ice Locust', desc = 'Fast swarmer. Shreds colonists in open ground.',
        tier = 'swarm',
        health = 15, speed = 7, damage = 8,
        thermalCore = 1, meat = 0,
        hostile = true, aggroRange = 20, leashRange = 999,
        packSize = { 4, 8 },
        color = { 0.5, 0.6, 0.7 },
        size = 0.25,
        noRetreat = true,
    },
    frost_wurm = {
        name = 'Frost Wurm', desc = 'Burrowing swarm breacher. Attacks walls.',
        tier = 'swarm',
        health = 150, speed = 2, damage = 30,
        thermalCore = 15, meat = 10,
        hostile = true, aggroRange = 12, leashRange = 999,
        color = { 0.35, 0.4, 0.55 },
        size = 1.2,
        breacher = true,
        noRetreat = true,
    },
    spawnling = {
        name = 'Spawnling', desc = 'Small hostile spawn. Fast, aggressive, hunts at night.',
        tier = 'swarm',
        health = 40, speed = 6, damage = 12,
        thermalCore = 2, meat = 2,
        hostile = true, aggroRange = 15, leashRange = 999,
        packSize = { 3, 7 },
        color = { 0.3, 0.25, 0.2 },
        size = 0.6,
        noRetreat = true,
        nightHunter = true,
    },
    skitterer = {
        name = 'Skitterer', desc = 'Tiny fast crawler. Swarms in large groups.',
        tier = 'swarm',
        health = 25, speed = 6, damage = 8,
        thermalCore = 1, meat = 1,
        hostile = true, aggroRange = 12, leashRange = 999,
        packSize = { 5, 10 },
        color = { 0.5, 0.55, 0.7 },
        size = 0.35,
        noRetreat = true,
    },
    giant_rat = {
        name = 'Permafrost Rat', desc = 'Permafrost vermin. Comes in massive waves.',
        tier = 'swarm',
        health = 18, speed = 7, damage = 5,
        thermalCore = 1, meat = 1,
        hostile = true, aggroRange = 8, leashRange = 999,
        packSize = { 6, 15 },
        color = { 0.4, 0.35, 0.3 },
        size = 0.25,
        noRetreat = true,
    },

    -- Eldritch swarm species
    nerve_worm = {
        name = 'Nerve Worm', desc = 'Burrowing parasite. Threads through permafrost cracks.',
        tier = 'swarm',
        health = 12, speed = 5, damage = 4,
        thermalCore = 0, meat = 0,
        hostile = true, aggroRange = 10, leashRange = 999,
        packSize = { 8, 20 },
        color = { 0.5, 0.3, 0.4 },
        size = 0.15,
        noRetreat = true,
    },
    nerve_tick = {
        name = 'Nerve Tick', desc = 'Latches on and feeds. Hard to spot, hard to remove.',
        tier = 'swarm',
        health = 8, speed = 6, damage = 3,
        thermalCore = 0, meat = 0,
        hostile = true, aggroRange = 8, leashRange = 999,
        packSize = { 10, 25 },
        color = { 0.45, 0.25, 0.35 },
        size = 0.1,
        noRetreat = true,
    },

    ---------------------------------------------------------------------------
    -- Rhea-2 desert species
    ---------------------------------------------------------------------------

    -- Small desert fauna
    sand_lizard = {
        name = 'Sand Lizard', desc = 'Fast-moving reptile. Vanishes into the dunes.',
        tier = 'small',
        health = 12, speed = 6.5, damage = 0,
        thermalCore = 1, meat = 1,
        hostile = false, fleeRange = 10,
        color = { 0.8, 0.7, 0.5 },
        size = 0.3,
        heatResistant = true,
    },
    dust_scarab = {
        name = 'Dust Scarab', desc = 'Tiny beetle. Harmless. Crunchy.',
        tier = 'small',
        health = 6, speed = 3, damage = 0,
        thermalCore = 0, meat = 0,
        hostile = false, fleeRange = 5,
        color = { 0.6, 0.45, 0.3 },
        size = 0.15,
        heatResistant = true,
    },
    canyon_sparrow = {
        name = 'Canyon Sparrow', desc = 'Small desert bird. Nests in cliff cracks.',
        tier = 'small',
        health = 8, speed = 7, damage = 0,
        thermalCore = 1, meat = 1,
        hostile = false, fleeRange = 12,
        color = { 0.75, 0.6, 0.45 },
        size = 0.25,
        heatResistant = true,
    },

    -- Medium desert fauna
    dune_stalker = {
        name = 'Dune Stalker', desc = 'Ambush predator. Desert camo makes it nearly invisible.',
        tier = 'medium',
        health = 70, speed = 5, damage = 16,
        thermalCore = 6, meat = 7,
        hostile = true, aggroRange = 13, leashRange = 22,
        color = { 0.85, 0.75, 0.55 },
        size = 0.75,
        heatResistant = true,
    },
    sand_viper = {
        name = 'Sand Viper', desc = 'Venomous strike. Defends its territory aggressively.',
        tier = 'medium',
        health = 45, speed = 4, damage = 20,
        thermalCore = 4, meat = 4,
        hostile = true, aggroRange = 8, leashRange = 16,
        color = { 0.7, 0.6, 0.4 },
        size = 0.6,
        heatResistant = true,
    },
    ridge_raptor = {
        name = 'Ridge Raptor', desc = 'Pack hunter. Runs prey down across open sand.',
        tier = 'medium',
        health = 55, speed = 5.5, damage = 14,
        thermalCore = 5, meat = 6,
        hostile = true, aggroRange = 12, leashRange = 24,
        packSize = { 2, 4 },
        color = { 0.75, 0.55, 0.35 },
        size = 0.7,
        heatResistant = true,
    },

    -- Medium-advanced desert fauna
    sand_wurm = {
        name = 'Sand Wurm', desc = 'Burrowing predator. Erupts from below, smashes through walls.',
        tier = 'medium',
        health = 180, speed = 2.5, damage = 30,
        thermalCore = 14, meat = 18,
        hostile = true, aggroRange = 10, leashRange = 22,
        color = { 0.8, 0.65, 0.4 },
        size = 1.4,
        breacher = true,
        heatResistant = true,
    },
    sun_scorpion = {
        name = 'Sun Scorpion', desc = 'Armored arachnid. Slow but hits like a sledgehammer.',
        tier = 'medium',
        health = 160, speed = 2, damage = 35,
        thermalCore = 12, meat = 14,
        hostile = true, aggroRange = 7, leashRange = 16,
        color = { 0.9, 0.7, 0.3 },
        size = 1.2,
        heatResistant = true,
    },
    wasteland_hyena = {
        name = 'Wasteland Hyena', desc = 'Scavenger packs. Circle and overwhelm.',
        tier = 'medium',
        health = 65, speed = 4.5, damage = 13,
        thermalCore = 5, meat = 6,
        hostile = true, aggroRange = 10, leashRange = 20,
        packSize = { 3, 5 },
        color = { 0.7, 0.55, 0.4 },
        size = 0.75,
        heatResistant = true,
    },

    -- Mega desert fauna
    desert_colossus = {
        name = 'Desert Colossus', desc = 'Massive sandstone-armored beast. Crushes walls underfoot.',
        tier = 'megafauna',
        health = 900, speed = 0.8, damage = 75,
        thermalCore = 90, meat = 65,
        hostile = true, aggroRange = 15, leashRange = 35,
        color = { 0.85, 0.7, 0.45 },
        size = 2.8,
        breacher = true,
        heatResistant = true,
    },
    heat_drake = {
        name = 'Heat Drake', desc = 'Fast for its size. Radiates searing heat.',
        tier = 'megafauna',
        health = 500, speed = 2.2, damage = 50,
        thermalCore = 60, meat = 35,
        hostile = true, aggroRange = 16, leashRange = 32,
        color = { 1.0, 0.5, 0.2 },
        size = 2.0,
        heatResistant = true,
    },
    dune_leviathan = {
        name = 'Dune Leviathan', desc = 'The desert made flesh. Largest thing under the twin suns.',
        tier = 'megafauna',
        health = 1200, speed = 0.6, damage = 85,
        thermalCore = 130, meat = 80,
        hostile = true, aggroRange = 20, leashRange = 40,
        color = { 0.9, 0.75, 0.5 },
        size = 3.2,
        breacher = true,
        heatResistant = true,
    },

    ---------------------------------------------------------------------------
    -- Morvos acid species
    ---------------------------------------------------------------------------

    -- Small acid fauna
    acid_mite = {
        name = 'Acid Mite', desc = 'Tiny. Harmless. Leaves corrosive trails.',
        tier = 'small',
        health = 5, speed = 3.5, damage = 0,
        thermalCore = 0, meat = 0,
        hostile = false, fleeRange = 6,
        color = { 0.4, 0.8, 0.2 },
        size = 0.15,
        acidImmune = true,
    },
    spore_crawler = {
        name = 'Spore Crawler', desc = 'Slow fungal creature. Flees at the slightest disturbance.',
        tier = 'small',
        health = 10, speed = 2, damage = 0,
        thermalCore = 1, meat = 1,
        hostile = false, fleeRange = 8,
        color = { 0.5, 0.7, 0.3 },
        size = 0.3,
        acidImmune = true,
    },
    slime_beetle = {
        name = 'Slime Beetle', desc = 'Docile beetle coated in mucus. Edible in a pinch.',
        tier = 'small',
        health = 8, speed = 2.5, damage = 0,
        thermalCore = 0, meat = 1,
        hostile = false, fleeRange = 5,
        color = { 0.55, 0.75, 0.15 },
        size = 0.2,
        acidImmune = true,
    },

    -- Medium acid fauna
    corrosion_hound = {
        name = 'Corrosion Hound', desc = 'Pack predator. Saliva eats through armor.',
        tier = 'medium',
        health = 65, speed = 4.5, damage = 15,
        thermalCore = 5, meat = 5,
        hostile = true, aggroRange = 11, leashRange = 22,
        packSize = { 2, 4 },
        color = { 0.45, 0.7, 0.2 },
        size = 0.7,
        acidImmune = true,
    },
    acid_spitter = {
        name = 'Acid Spitter', desc = 'Territorial. Launches corrosive bile at intruders.',
        tier = 'medium',
        health = 55, speed = 3, damage = 22,
        thermalCore = 6, meat = 4,
        hostile = true, aggroRange = 14, leashRange = 20,
        color = { 0.6, 0.85, 0.1 },
        size = 0.8,
        acidImmune = true,
    },
    fungal_stalker = {
        name = 'Fungal Stalker', desc = 'Ambush predator. Hunts at night, merges with the spore fields.',
        tier = 'medium',
        health = 75, speed = 4, damage = 18,
        thermalCore = 7, meat = 6,
        hostile = true, aggroRange = 12, leashRange = 24,
        color = { 0.35, 0.6, 0.25 },
        size = 0.8,
        nightHunter = true,
        acidImmune = true,
    },

    -- Medium-advanced acid fauna
    bile_brute = {
        name = 'Bile Brute', desc = 'Hulking toxic mass. Smashes walls. Leaves poison in its wake.',
        tier = 'medium',
        health = 200, speed = 1.8, damage = 32,
        thermalCore = 14, meat = 16,
        hostile = true, aggroRange = 9, leashRange = 20,
        color = { 0.5, 0.65, 0.1 },
        size = 1.5,
        breacher = true,
        acidImmune = true,
    },
    caustic_wurm = {
        name = 'Caustic Wurm', desc = 'Burrower. Leaves acid-filled tunnels behind it.',
        tier = 'medium',
        health = 170, speed = 2.5, damage = 28,
        thermalCore = 12, meat = 14,
        hostile = true, aggroRange = 10, leashRange = 22,
        color = { 0.55, 0.8, 0.15 },
        size = 1.3,
        breacher = true,
        acidImmune = true,
    },
    plague_carrier = {
        name = 'Plague Carrier', desc = 'Bloated vector. Spreads disease on contact.',
        tier = 'medium',
        health = 130, speed = 2, damage = 10,
        thermalCore = 8, meat = 8,
        hostile = true, aggroRange = 8, leashRange = 18,
        color = { 0.65, 0.75, 0.2 },
        size = 1.1,
        acidImmune = true,
    },

    -- Mega acid fauna
    acid_titan = {
        name = 'Acid Titan', desc = 'Massive. Everything it touches corrodes to nothing.',
        tier = 'megafauna',
        health = 850, speed = 1.0, damage = 70,
        thermalCore = 85, meat = 50,
        hostile = true, aggroRange = 15, leashRange = 35,
        color = { 0.4, 0.9, 0.15 },
        size = 2.6,
        breacher = true,
        acidImmune = true,
    },
    the_dissolvent = {
        name = 'The Dissolvent', desc = 'Boss-tier predator. Acid aura melts anything nearby.',
        tier = 'megafauna',
        health = 700, speed = 1.5, damage = 55,
        thermalCore = 70, meat = 30,
        hostile = true, aggroRange = 18, leashRange = 35,
        color = { 0.3, 0.95, 0.1 },
        size = 2.2,
        fearAura = 10,
        acidImmune = true,
    },
    mire_colossus = {
        name = 'Mire Colossus', desc = 'Slow mountain of toxic flesh. Exudes poisonous cloud.',
        tier = 'megafauna',
        health = 1100, speed = 0.6, damage = 80,
        thermalCore = 110, meat = 70,
        hostile = true, aggroRange = 14, leashRange = 30,
        color = { 0.35, 0.7, 0.2 },
        size = 3.0,
        breacher = true,
        acidImmune = true,
    },

    ---------------------------------------------------------------------------
    -- Nemaea automaton species (mechanical, no organic wildlife)
    ---------------------------------------------------------------------------

    -- Small automatons
    scout_drone = {
        name = 'Scout Drone', desc = 'Fast recon unit. Passive until provoked, then calls reinforcements.',
        tier = 'small',
        health = 20, speed = 6, damage = 4,
        thermalCore = 0, meat = 0, components = 2, metal = 1,
        hostile = false, fleeRange = 6,
        aggroRange = 8, leashRange = 20,
        color = { 0.6, 0.62, 0.65 },
        size = 0.35,
        mechanical = true,
        radiationImmune = true,
        vacuumImmune = true,
    },
    maintenance_bot = {
        name = 'Maintenance Bot', desc = 'Slow repair unit. Flees on contact. Scavenges wreckage.',
        tier = 'small',
        health = 15, speed = 2, damage = 0,
        thermalCore = 0, meat = 0, components = 3, metal = 2,
        hostile = false, fleeRange = 10,
        color = { 0.5, 0.52, 0.55 },
        size = 0.4,
        mechanical = true,
        radiationImmune = true,
        vacuumImmune = true,
    },

    -- Medium automatons
    patrol_automaton = {
        name = 'Patrol Automaton', desc = 'Armed sentry. Patrols fixed routes. Territorial.',
        tier = 'medium',
        health = 90, speed = 3, damage = 16,
        thermalCore = 0, meat = 0, components = 5, metal = 4,
        hostile = true, aggroRange = 12, leashRange = 20,
        color = { 0.55, 0.55, 0.58 },
        size = 0.8,
        mechanical = true,
        radiationImmune = true,
        vacuumImmune = true,
    },
    enforcer_unit = {
        name = 'Enforcer Unit', desc = 'Heavy combat chassis. Aggressive pursuit protocol.',
        tier = 'medium',
        health = 140, speed = 3, damage = 22,
        thermalCore = 0, meat = 0, components = 6, metal = 5,
        hostile = true, aggroRange = 14, leashRange = 25,
        color = { 0.4, 0.38, 0.42 },
        size = 1.0,
        mechanical = true,
        radiationImmune = true,
        vacuumImmune = true,
    },
    salvage_drone = {
        name = 'Salvage Drone', desc = 'Scavenger pack. Strips wreckage for parts. Fights if cornered.',
        tier = 'medium',
        health = 60, speed = 3.5, damage = 10,
        thermalCore = 0, meat = 0, components = 4, metal = 3,
        hostile = true, aggroRange = 8, leashRange = 18,
        packSize = { 2, 3 },
        color = { 0.65, 0.5, 0.35 },
        size = 0.7,
        mechanical = true,
        radiationImmune = true,
        vacuumImmune = true,
    },

    -- Medium-advanced automatons
    siege_automaton = {
        name = 'Siege Automaton', desc = 'Breacher unit. Slow, heavy plating. Smashes through walls.',
        tier = 'medium',
        health = 250, speed = 1.5, damage = 35,
        thermalCore = 0, meat = 0, components = 10, metal = 8,
        hostile = true, aggroRange = 10, leashRange = 20,
        color = { 0.45, 0.42, 0.4 },
        size = 1.5,
        mechanical = true,
        breacher = true,
        radiationImmune = true,
        vacuumImmune = true,
    },
    hunter_killer = {
        name = 'Hunter-Killer', desc = 'Fast pursuit unit. Relentless tracking protocol. Does not disengage.',
        tier = 'medium',
        health = 100, speed = 5.5, damage = 24,
        thermalCore = 0, meat = 0, components = 7, metal = 4,
        hostile = true, aggroRange = 18, leashRange = 999,
        color = { 0.3, 0.28, 0.32 },
        size = 0.9,
        mechanical = true,
        radiationImmune = true,
        vacuumImmune = true,
    },
    containment_unit = {
        name = 'Containment Unit', desc = 'Capture protocol. Subdues targets non-lethally. Drags them to holding.',
        tier = 'medium',
        health = 130, speed = 3, damage = 12,
        thermalCore = 0, meat = 0, components = 8, metal = 6,
        hostile = true, aggroRange = 12, leashRange = 22,
        color = { 0.5, 0.55, 0.6 },
        size = 1.1,
        mechanical = true,
        radiationImmune = true,
        vacuumImmune = true,
    },

    -- Mega automatons
    titan_automaton = {
        name = 'Titan Automaton', desc = 'Massive war platform. Breaches anything. Shakes the ground.',
        tier = 'megafauna',
        health = 800, speed = 1, damage = 70,
        thermalCore = 0, meat = 0, components = 25, metal = 20,
        hostile = true, aggroRange = 16, leashRange = 35,
        color = { 0.35, 0.33, 0.36 },
        size = 2.5,
        mechanical = true,
        breacher = true,
        radiationImmune = true,
        vacuumImmune = true,
    },
    the_warden = {
        name = 'The Warden', desc = 'Supreme automaton. Central command node. Killing it disrupts all nearby units.',
        tier = 'megafauna',
        health = 1200, speed = 1.5, damage = 60,
        thermalCore = 0, meat = 0, components = 40, metal = 30,
        hostile = true, aggroRange = 20, leashRange = 999,
        color = { 0.7, 0.25, 0.2 },
        size = 2.8,
        mechanical = true,
        fearAura = 12,
        radiationImmune = true,
        vacuumImmune = true,
    },
    dyson_sentinel = {
        name = 'Dyson Sentinel', desc = 'Orbital defense unit. Extremely tough armor plating. Relic of the Sphere.',
        tier = 'megafauna',
        health = 1500, speed = 0.8, damage = 85,
        thermalCore = 0, meat = 0, components = 50, metal = 40,
        hostile = true, aggroRange = 18, leashRange = 40,
        color = { 0.25, 0.22, 0.28 },
        size = 3.0,
        mechanical = true,
        breacher = true,
        radiationImmune = true,
        vacuumImmune = true,
    },

    ---------------------------------------------------------------------------
    -- Gaia A^1x species (temperate fauna + Baldrungen insectoid undead)
    ---------------------------------------------------------------------------

    -- Small Gaia fauna (passive, temperate)
    forest_rabbit = {
        name = 'Forest Rabbit', desc = 'Soft brown fur. Harmless. Flees at the slightest sound.',
        tier = 'small',
        health = 10, speed = 5.5, damage = 0,
        thermalCore = 1, meat = 2,
        hostile = false, fleeRange = 10,
        color = { 0.55, 0.4, 0.3 },
        size = 0.3,
    },
    songbird = {
        name = 'Songbird', desc = 'Tiny bright-feathered bird. Pleasant calls at dawn.',
        tier = 'small',
        health = 5, speed = 7, damage = 0,
        thermalCore = 0, meat = 0,
        hostile = false, fleeRange = 14,
        color = { 0.3, 0.6, 0.35 },
        size = 0.15,
    },
    meadow_vole = {
        name = 'Meadow Vole', desc = 'Small burrowing rodent. Harmless grass-eater.',
        tier = 'small',
        health = 8, speed = 4, damage = 0,
        thermalCore = 0, meat = 1,
        hostile = false, fleeRange = 8,
        color = { 0.5, 0.45, 0.35 },
        size = 0.2,
    },

    -- Medium Gaia fauna (natural predators)
    timber_predator = {
        name = 'Timber Predator', desc = 'Wolf-like pack hunter. Patrols the forest edge at dusk.',
        tier = 'medium',
        health = 65, speed = 4.5, damage = 14,
        thermalCore = 5, meat = 8,
        hostile = true, aggroRange = 10, leashRange = 22,
        packSize = { 2, 4 },
        color = { 0.45, 0.4, 0.3 },
        size = 0.75,
    },
    brook_bear = {
        name = 'Brook Bear', desc = 'Territorial omnivore. Fishes the streams. Do not approach cubs.',
        tier = 'medium',
        health = 150, speed = 2.5, damage = 28,
        thermalCore = 10, meat = 18,
        hostile = true, aggroRange = 7, leashRange = 16,
        color = { 0.4, 0.3, 0.2 },
        size = 1.0,
    },
    grove_stalker = {
        name = 'Grove Stalker', desc = 'Ambush predator. Hunts at night from the canopy.',
        tier = 'medium',
        health = 80, speed = 4, damage = 20,
        thermalCore = 7, meat = 7,
        hostile = true, aggroRange = 12, leashRange = 24,
        color = { 0.3, 0.35, 0.2 },
        size = 0.8,
        nightHunter = true,
    },

    -- Medium-advanced Gaia fauna (Baldrungen's insectoid undead)
    husk_crawler = {
        name = 'Husk Crawler', desc = 'Chitinous insectoid corpse. Fast, mindless, swarms in packs. Baldrungen\'s footsoldiers.',
        tier = 'medium',
        health = 50, speed = 5, damage = 12,
        thermalCore = 3, meat = 2,
        hostile = true, aggroRange = 14, leashRange = 999,
        packSize = { 3, 5 },
        color = { 0.6, 0.55, 0.2 },
        size = 0.6,
        noRetreat = true,
    },
    bone_beetle = {
        name = 'Bone Beetle', desc = 'Armored undead insect. Slow but breaks through walls. Exoskeleton of fused bone.',
        tier = 'medium',
        health = 180, speed = 1.8, damage = 30,
        thermalCore = 8, meat = 5,
        hostile = true, aggroRange = 8, leashRange = 20,
        color = { 0.75, 0.7, 0.5 },
        size = 1.2,
        breacher = true,
    },
    rot_wasp = {
        name = 'Rot Wasp', desc = 'Fast venomous flier. Decaying wings somehow still carry it. Hunts in swarms.',
        tier = 'medium',
        health = 35, speed = 6, damage = 15,
        thermalCore = 2, meat = 1,
        hostile = true, aggroRange = 16, leashRange = 999,
        packSize = { 2, 4 },
        color = { 0.5, 0.3, 0.5 },
        size = 0.5,
        noRetreat = true,
    },

    -- Mega Gaia fauna (Baldrungen-spawned horrors)
    brood_mother = {
        name = 'Brood Mother', desc = 'Massive insectoid queen. Spawns husk_crawlers from its bloated abdomen. Kill it before the swarm grows.',
        tier = 'megafauna',
        health = 600, speed = 1.2, damage = 40,
        thermalCore = 50, meat = 30,
        hostile = true, aggroRange = 14, leashRange = 30,
        color = { 0.55, 0.5, 0.15 },
        size = 2.2,
    },
    the_emergence = {
        name = 'The Emergence', desc = 'Insectoid titan. Baldrungen\'s rage given chitinous form. Breaches everything in its path.',
        tier = 'megafauna',
        health = 1000, speed = 1, damage = 75,
        thermalCore = 100, meat = 40,
        hostile = true, aggroRange = 18, leashRange = 999,
        color = { 0.3, 0.2, 0.05 },
        size = 3.0,
        breacher = true,
        fearAura = 14,
    },
    baldrungen_tendril = {
        name = 'Baldrungen Tendril', desc = 'Living root-tentacle punching through the crust. Massive, slow, impossibly tough. The planet itself reaching up.',
        tier = 'megafauna',
        health = 1400, speed = 0.5, damage = 65,
        thermalCore = 80, meat = 0,
        hostile = true, aggroRange = 12, leashRange = 25,
        color = { 0.2, 0.15, 0.1 },
        size = 3.5,
        breacher = true,
    },

    ---------------------------------------------------------------------------
    -- Nerthus-9 ocean species
    ---------------------------------------------------------------------------

    -- Small ocean fauna (passive)
    tide_crab = {
        name = 'Tide Crab', desc = 'Small crustacean. Scuttles away when approached.',
        tier = 'small',
        health = 12, speed = 4, damage = 1,
        thermalCore = 1, meat = 2,
        hostile = false, fleeRange = 7,
        color = { 0.3, 0.5, 0.7 },
        size = 0.3,
        aquatic = true,
    },
    reef_fish = {
        name = 'Reef Fish', desc = 'Tiny schooling fish. Barely worth catching individually.',
        tier = 'small',
        health = 5, speed = 6, damage = 0,
        thermalCore = 0, meat = 1,
        hostile = false, fleeRange = 10,
        color = { 0.4, 0.6, 0.8 },
        size = 0.15,
        aquatic = true,
    },
    kelp_drifter = {
        name = 'Kelp Drifter', desc = 'Slow-moving algae grazer. Harmless.',
        tier = 'small',
        health = 18, speed = 2, damage = 0,
        thermalCore = 1, meat = 2,
        hostile = false, fleeRange = 5,
        color = { 0.2, 0.55, 0.35 },
        size = 0.4,
        aquatic = true,
    },

    -- Medium ocean fauna (territorial)
    depth_lurker = {
        name = 'Depth Lurker', desc = 'Ambush predator. Lies still until prey passes overhead.',
        tier = 'medium',
        health = 80, speed = 3, damage = 18,
        thermalCore = 6, meat = 8,
        hostile = true, aggroRange = 6, leashRange = 14,
        color = { 0.15, 0.2, 0.45 },
        size = 0.8,
        aquatic = true,
    },
    reef_shark = {
        name = 'Reef Shark', desc = 'Fast and relentless. Blood in the water draws more.',
        tier = 'medium',
        health = 70, speed = 5, damage = 16,
        thermalCore = 5, meat = 10,
        hostile = true, aggroRange = 12, leashRange = 25,
        color = { 0.35, 0.4, 0.5 },
        size = 0.9,
        aquatic = true,
    },
    pressure_eel = {
        name = 'Pressure Eel', desc = 'Venomous deep-water eel. Hunts in small groups.',
        tier = 'medium',
        health = 55, speed = 4, damage = 14,
        thermalCore = 4, meat = 5,
        hostile = true, aggroRange = 10, leashRange = 20,
        packSize = { 2, 3 },
        color = { 0.25, 0.35, 0.55 },
        size = 0.6,
        aquatic = true,
    },

    -- Medium-advanced ocean fauna
    kraken_spawn = {
        name = 'Kraken Spawn', desc = 'Juvenile kraken. Tentacles grab and crush.',
        tier = 'medium',
        health = 160, speed = 2, damage = 28,
        thermalCore = 12, meat = 18,
        hostile = true, aggroRange = 8, leashRange = 18,
        color = { 0.2, 0.25, 0.4 },
        size = 1.3,
        aquatic = true,
    },
    abyssal_hunter = {
        name = 'Abyssal Hunter', desc = 'Fast deep-sea predator. Hunts at night, retreats to depth by day.',
        tier = 'medium',
        health = 100, speed = 5, damage = 24,
        thermalCore = 9, meat = 8,
        hostile = true, aggroRange = 14, leashRange = 28,
        color = { 0.1, 0.1, 0.3 },
        size = 1.0,
        nightHunter = true,
        aquatic = true,
    },
    barnacle_titan_juvenile = {
        name = 'Barnacle Titan Juvenile', desc = 'Young armored behemoth. Slow but nearly impervious.',
        tier = 'medium',
        health = 200, speed = 1.5, damage = 20,
        thermalCore = 14, meat = 22,
        hostile = true, aggroRange = 6, leashRange = 15,
        color = { 0.35, 0.4, 0.35 },
        size = 1.4,
        aquatic = true,
    },

    -- Mega ocean fauna (boss creatures)
    storm_leviathan = {
        name = 'Storm Leviathan', desc = 'Massive sea beast. Alarmingly fast for its size.',
        tier = 'megafauna',
        health = 700, speed = 2.0, damage = 65,
        thermalCore = 90, meat = 55,
        hostile = true, aggroRange = 18, leashRange = 40,
        color = { 0.2, 0.35, 0.6 },
        size = 2.5,
        aquatic = true,
    },
    the_depth_mother = {
        name = 'The Depth Mother', desc = 'Spawns minions endlessly. Kill her or drown in her brood.',
        tier = 'megafauna',
        health = 600, speed = 1.2, damage = 40,
        thermalCore = 75, meat = 45,
        hostile = true, aggroRange = 16, leashRange = 35,
        color = { 0.15, 0.2, 0.5 },
        size = 2.2,
        aquatic = true,
    },
    tidal_colossus = {
        name = 'Tidal Colossus', desc = 'Living tidal wave. Smashes through everything in its path.',
        tier = 'megafauna',
        health = 900, speed = 0.8, damage = 80,
        thermalCore = 110, meat = 65,
        hostile = true, aggroRange = 14, leashRange = 30,
        color = { 0.25, 0.4, 0.65 },
        size = 3.0,
        breacher = true,
        aquatic = true,
    },

    ---------------------------------------------------------------------------
    -- Paxtera Prime species (temperate / corporate)
    ---------------------------------------------------------------------------

    -- Small temperate fauna (passive)
    field_hare = {
        name = 'Field Hare', desc = 'Fast brown hare. Bolts at the first sign of trouble.',
        tier = 'small',
        health = 12, speed = 6, damage = 0,
        thermalCore = 1, meat = 2,
        hostile = false, fleeRange = 9,
        color = { 0.6, 0.45, 0.3 },
        size = 0.35,
    },
    grain_bird = {
        name = 'Grain Bird', desc = 'Common field bird. Flees immediately.',
        tier = 'small',
        health = 8, speed = 7, damage = 0,
        thermalCore = 0, meat = 1,
        hostile = false, fleeRange = 12,
        color = { 0.55, 0.5, 0.35 },
        size = 0.2,
    },
    orchard_snake = {
        name = 'Orchard Snake', desc = 'Small constrictor. Hides in tall grass.',
        tier = 'small',
        health = 10, speed = 4, damage = 2,
        thermalCore = 1, meat = 1,
        hostile = false, fleeRange = 6,
        color = { 0.35, 0.5, 0.25 },
        size = 0.25,
    },

    -- Medium temperate fauna (territorial)
    timber_wolf = {
        name = 'Timber Wolf', desc = 'Classic pack hunter. Coordinates attacks with the pack.',
        tier = 'medium',
        health = 65, speed = 4.5, damage = 14,
        thermalCore = 5, meat = 8,
        hostile = true, aggroRange = 10, leashRange = 22,
        packSize = { 2, 4 },
        color = { 0.45, 0.4, 0.35 },
        size = 0.7,
    },
    plains_bear = {
        name = 'Plains Bear', desc = 'Tough territorial omnivore. Best avoided.',
        tier = 'medium',
        health = 130, speed = 2.5, damage = 26,
        thermalCore = 10, meat = 16,
        hostile = true, aggroRange = 7, leashRange = 16,
        color = { 0.5, 0.4, 0.3 },
        size = 1.0,
    },
    wild_boar = {
        name = 'Wild Boar', desc = 'Charges when threatened. Surprisingly fast.',
        tier = 'medium',
        health = 75, speed = 4, damage = 16,
        thermalCore = 4, meat = 10,
        hostile = true, aggroRange = 8, leashRange = 18,
        color = { 0.4, 0.35, 0.25 },
        size = 0.7,
    },

    -- Medium-advanced temperate fauna
    feral_bull = {
        name = 'Feral Bull', desc = 'Escaped livestock gone wild. Charges through fences and walls.',
        tier = 'medium',
        health = 180, speed = 3.5, damage = 30,
        thermalCore = 12, meat = 22,
        hostile = true, aggroRange = 8, leashRange = 20,
        color = { 0.5, 0.35, 0.2 },
        size = 1.2,
        breacher = true,
    },
    apex_cat = {
        name = 'Apex Cat', desc = 'Nocturnal ambush predator. Silent and lethal.',
        tier = 'medium',
        health = 90, speed = 5.5, damage = 22,
        thermalCore = 7, meat = 7,
        hostile = true, aggroRange = 12, leashRange = 25,
        color = { 0.55, 0.45, 0.3 },
        size = 0.9,
        nightHunter = true,
    },
    razorback_hog = {
        name = 'Razorback Hog', desc = 'Armored feral pig. Hunts in small sounders.',
        tier = 'medium',
        health = 110, speed = 3.5, damage = 20,
        thermalCore = 8, meat = 14,
        hostile = true, aggroRange = 9, leashRange = 20,
        packSize = { 2, 3 },
        color = { 0.45, 0.35, 0.25 },
        size = 0.85,
    },

    -- Mega temperate fauna (boss creatures)
    mammona_enforcer_mech = {
        name = 'Mammona Enforcer Mech', desc = 'Corporate security drone. Heavily armed and armored.',
        tier = 'megafauna',
        health = 650, speed = 2.0, damage = 55,
        thermalCore = 60, meat = 0,
        hostile = true, aggroRange = 16, leashRange = 35,
        color = { 0.7, 0.65, 0.4 },
        size = 2.0,
    },
    great_elk = {
        name = 'Great Elk', desc = 'Massive herbivore. Docile unless cornered or provoked.',
        tier = 'megafauna',
        health = 400, speed = 2.5, damage = 35,
        thermalCore = 35, meat = 45,
        hostile = false, fleeRange = 0,
        aggroRange = 5, leashRange = 15,
        color = { 0.5, 0.45, 0.3 },
        size = 2.0,
    },
    territorial_megabear = {
        name = 'Territorial Megabear', desc = 'Boss-tier apex predator. Will tear through walls to reach prey.',
        tier = 'megafauna',
        health = 800, speed = 1.8, damage = 70,
        thermalCore = 85, meat = 60,
        hostile = true, aggroRange = 14, leashRange = 30,
        color = { 0.4, 0.3, 0.2 },
        size = 2.5,
        breacher = true,
    },

    ---------------------------------------------------------------------------
    -- Xenolith — Ancient insectoid species from the Bootes Void
    -- Nearly extinct after the Heaven's Atlas events. Survivors are
    -- solitary queens or dormant eggs found in derelict bio-ships.
    -- Bio-engineered, not natural. Mammona subsidiary BioVault Inc.
    -- may be attempting to revive the species from recovered eggs.
    ---------------------------------------------------------------------------

    xenolith_queen = {
        name = 'Xenolith Queen', desc = 'Solitary queen. Massive, armored, desperate. Chitin deflects small arms. Clicks and chitters that shake the hull. Last of her hive, or the first of a new one.',
        tier = 'eldritch',
        health = 2000, speed = 1.0, damage = 80,
        thermalCore = 200, meat = 0,
        hostile = true, aggroRange = 20, leashRange = 999,
        color = { 0.15, 0.08, 0.2 },
        size = 3.5,
        vacuumImmune = true,
        radiationImmune = true,
        acidImmune = true,
        boss = true,
        breacher = true,
        armor = 0.5,  -- 50% damage reduction
        spawnOnDeath = { species = 'xenolith_larva', count = 4 },
    },
    xenolith_drone = {
        name = 'Xenolith Drone', desc = 'Worker-soldier. Eyeless, covered in tendrils. Talons cut through steel. Clicks when it hunts.',
        tier = 'megafauna',
        health = 300, speed = 3.5, damage = 40,
        thermalCore = 30, meat = 0,
        hostile = true, aggroRange = 16, leashRange = 40,
        color = { 0.2, 0.12, 0.25 },
        size = 1.5,
        vacuumImmune = true,
        radiationImmune = true,
        packSize = { min = 2, max = 5 },
    },
    xenolith_larva = {
        name = 'Xenolith Larva', desc = 'Freshly hatched. Fragile but fast. Swarms overwhelm. Will mature into a drone if not killed quickly.',
        tier = 'swarm',
        health = 40, speed = 5.0, damage = 12,
        thermalCore = 5, meat = 0,
        hostile = true, aggroRange = 12, leashRange = 30,
        color = { 0.25, 0.15, 0.3 },
        size = 0.5,
        vacuumImmune = true,
        packSize = { min = 4, max = 10 },
    },
    xenolith_spore = {
        name = 'Xenolith Spore', desc = 'Drifting spore cluster. Latches onto biomass and starts growing. Kill it before it roots.',
        tier = 'small',
        health = 15, speed = 1.0, damage = 0,
        thermalCore = 2, meat = 0,
        hostile = false, fleeRange = 0,
        color = { 0.3, 0.15, 0.35 },
        size = 0.3,
        vacuumImmune = true,
    },
}
