-- building_defs_space.lua — Ship module and space building definitions
local Tiles = require('src.world.tiles')

return {
    ---------------------------------------------------------------------------
    -- Ship structural
    ---------------------------------------------------------------------------
    ship_hull_wall = {
        name = 'Ship Hull Wall', desc = 'Reinforced hull plating. Withstands vacuum and minor impacts.',
        w = 1, h = 1,
        tile = Tiles.WALL_METAL or 4,
        cost = { steel = 3 },
        category = 'structure',
    },
    ship_floor = {
        name = 'Ship Floor Plate', desc = 'Standard deck plating for ship interiors.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_METAL or 3,
        cost = { steel = 1 },
        category = 'structure',
    },
    ship_airlock = {
        name = 'Airlock', desc = 'Pressurized door. Controlled entry/exit for EVA and boarding defense.',
        w = 1, h = 1,
        tile = Tiles.DOOR_METAL or 9,
        cost = { steel = 5, components = 3 },
        entitySpawn = 'ship_module',
        shipSystemType = 'airlock',
        category = 'structure',
    },

    ---------------------------------------------------------------------------
    -- Ship core systems (required modules)
    ---------------------------------------------------------------------------
    mini_reactor = {
        name = 'Mini Reactor', desc = 'Compact power source for small ships. Low output, no overdrive.',
        w = 1, h = 1,
        cost = { steel = 15, components = 10, circuit = 5 },
        entitySpawn = 'ship_module',
        shipSystemType = 'mini_reactor',
        powerOutput = 50,
        category = 'power',
    },
    cockpit = {
        name = 'Cockpit', desc = 'Flight control station. Pilot required for navigation.',
        w = 2, h = 2,
        tile = Tiles.FLOOR_METAL or 3,
        cost = { steel = 10, components = 5, circuit = 3 },
        entitySpawn = 'ship_module',
        shipSystemType = 'cockpit',
        powerDraw = 10,
        category = 'colony',
    },
    bridge = {
        name = 'Bridge', desc = 'Command center for colony ships. Better sensors and autopilot.',
        w = 3, h = 3,
        tile = Tiles.FLOOR_METAL or 3,
        cost = { steel = 25, components = 15, circuit = 10 },
        entitySpawn = 'ship_module',
        shipSystemType = 'bridge',
        powerDraw = 20,
        category = 'colony',
    },
    ship_engine = {
        name = 'Engine', desc = 'Thrust drive for scout ships. Burns fuel for propulsion.',
        w = 2, h = 3,
        tile = Tiles.FLOOR_METAL or 3,
        cost = { steel = 20, components = 10, circuit = 5 },
        entitySpawn = 'ship_module',
        shipSystemType = 'engine',
        powerDraw = 15,
        category = 'power',
    },
    engine_bay = {
        name = 'Engine Bay', desc = 'Heavy thrust array for colony ships. High fuel consumption.',
        w = 3, h = 4,
        tile = Tiles.FLOOR_METAL or 3,
        cost = { steel = 50, components = 25, circuit = 15 },
        entitySpawn = 'ship_module',
        shipSystemType = 'engine_bay',
        powerDraw = 30,
        category = 'power',
    },
    ship_life_support = {
        name = 'Life Support', desc = 'Compact O2 generator and CO2 scrubber for small ships.',
        w = 1, h = 2,
        tile = Tiles.FLOOR_METAL or 3,
        cost = { steel = 8, components = 5, pipe = 3 },
        entitySpawn = 'ship_module',
        shipSystemType = 'life_support',
        powerDraw = 10,
        category = 'atmosphere',
    },
    life_support_array = {
        name = 'Life Support Array', desc = 'Full atmospheric system for colony ships.',
        w = 2, h = 3,
        tile = Tiles.FLOOR_METAL or 3,
        cost = { steel = 20, components = 15, pipe = 10 },
        entitySpawn = 'ship_module',
        shipSystemType = 'life_support_array',
        powerDraw = 25,
        category = 'atmosphere',
    },

    ---------------------------------------------------------------------------
    -- Ship weapons (usable on ships AND planet defenses)
    ---------------------------------------------------------------------------
    weapon_mount = {
        name = 'Weapon Mount', desc = 'Generic hardpoint. Accepts any weapon module.',
        w = 1, h = 1,
        cost = { steel = 15, components = 8 },
        entitySpawn = 'ship_module',
        shipSystemType = 'weapon_mount',
        powerDraw = 20,
        category = 'defense',
    },
    railgun = {
        name = 'Railgun', desc = 'Electromagnetic accelerator. Extreme range, devastating penetration. Slow to charge.',
        w = 2, h = 1,
        cost = { steel = 30, components = 20, circuit = 15 },
        entitySpawn = 'ship_module',
        shipSystemType = 'weapon_mount',
        weaponType = 'railgun',
        powerDraw = 40,
        category = 'defense',
        weaponStats = { damage = 45, range = 30, fireRate = 8.0, accuracy = 0.7, penetration = 0.9 },
    },
    ship_laser = {
        name = 'Laser Battery', desc = 'Focused energy beam. Fast fire rate, precise targeting. Reduced by shields.',
        w = 1, h = 1,
        cost = { steel = 20, components = 15, circuit = 10 },
        entitySpawn = 'ship_module',
        shipSystemType = 'weapon_mount',
        weaponType = 'laser',
        powerDraw = 25,
        category = 'defense',
        weaponStats = { damage = 12, range = 20, fireRate = 1.5, accuracy = 0.85, penetration = 0.3 },
    },
    missile_launcher = {
        name = 'Missile Launcher', desc = 'Fires guided warheads. High damage, limited ammo. Reload at stations.',
        w = 1, h = 1,
        cost = { steel = 25, components = 15 },
        entitySpawn = 'ship_module',
        shipSystemType = 'weapon_mount',
        weaponType = 'missile',
        powerDraw = 10,
        category = 'defense',
        weaponStats = { damage = 35, range = 25, fireRate = 5.0, accuracy = 0.75, ammo = 12 },
    },
    heavy_warhead_launcher = {
        name = 'Heavy Warhead Launcher', desc = 'Fires heavy warheads. Area damage on impact. Very limited ammo.',
        w = 2, h = 1,
        cost = { steel = 40, components = 25, circuit = 10 },
        entitySpawn = 'ship_module',
        shipSystemType = 'weapon_mount',
        weaponType = 'heavy_warhead',
        powerDraw = 15,
        category = 'defense',
        weaponStats = { damage = 60, range = 20, fireRate = 10.0, accuracy = 0.6, ammo = 6, areaDamage = 20 },
    },
    emp_missile_launcher = {
        name = 'EMP Missile Launcher', desc = 'Fires electromagnetic pulse warheads. Disables ship systems without hull damage.',
        w = 1, h = 1,
        cost = { steel = 20, components = 20, circuit = 15 },
        entitySpawn = 'ship_module',
        shipSystemType = 'weapon_mount',
        weaponType = 'emp_missile',
        powerDraw = 15,
        category = 'defense',
        weaponStats = { damage = 5, range = 22, fireRate = 6.0, accuracy = 0.7, ammo = 8, empDuration = 15 },
    },
    emp_mine_launcher = {
        name = 'EMP Mine Layer', desc = 'Deploys proximity-triggered EMP mines. Disables nearby ships on detonation.',
        w = 1, h = 1,
        cost = { steel = 15, components = 15, circuit = 20 },
        entitySpawn = 'ship_module',
        shipSystemType = 'weapon_mount',
        weaponType = 'emp_mine',
        powerDraw = 5,
        category = 'defense',
        weaponStats = { damage = 3, range = 5, fireRate = 10.0, ammo = 6, empDuration = 20, deployable = true },
    },
    emp_field_generator = {
        name = 'EMP Field Generator', desc = 'Blankets the area in electromagnetic noise. Kills all electronics in range. Yours too.',
        w = 2, h = 2,
        cost = { steel = 30, components = 25, circuit = 25 },
        entitySpawn = 'ship_module',
        shipSystemType = 'emp_field',
        powerDraw = 60,
        category = 'defense',
        weaponStats = { radius = 8, empDuration = 0, selfDamage = true },
    },
    nano_dump_launcher = {
        name = 'Nano Dump Launcher', desc = 'Launches a cloud of hostile nanomachines that shred ship modules. Ignores shields.',
        w = 1, h = 1,
        cost = { steel = 25, components = 30, circuit = 20 },
        entitySpawn = 'ship_module',
        shipSystemType = 'weapon_mount',
        weaponType = 'nano_dump',
        powerDraw = 20,
        category = 'defense',
        weaponStats = { damage = 8, range = 12, fireRate = 8.0, accuracy = 0.9, ammo = 4, ignoresShields = true, systemDamageMult = 3.0 },
    },
    point_defense = {
        name = 'Point Defense', desc = 'Automated close-range interceptor. Shoots down incoming missiles and mines.',
        w = 1, h = 1,
        cost = { steel = 15, components = 10, circuit = 8 },
        entitySpawn = 'ship_module',
        shipSystemType = 'weapon_mount',
        weaponType = 'point_defense',
        powerDraw = 15,
        category = 'defense',
        weaponStats = { damage = 5, range = 8, fireRate = 0.5, accuracy = 0.9, interceptor = true },
    },
    shield_generator = {
        name = 'Shield Generator', desc = 'Energy barrier absorbing incoming fire. Drains power fast.',
        w = 2, h = 2,
        cost = { steel = 30, components = 20, circuit = 15 },
        entitySpawn = 'ship_module',
        shipSystemType = 'shield_generator',
        powerDraw = 50,
        category = 'defense',
    },
    sensor_array = {
        name = 'Sensor Array', desc = 'Extends detection range. Reveals distant contacts and hazards.',
        w = 1, h = 1,
        cost = { steel = 5, components = 8, circuit = 5 },
        entitySpawn = 'ship_module',
        shipSystemType = 'sensor_array',
        powerDraw = 10,
        category = 'colony',
    },
    comms_array = {
        name = 'Comms Array', desc = 'Long-range communications. Hail stations, send distress calls.',
        w = 1, h = 1,
        cost = { steel = 5, components = 5, circuit = 8 },
        entitySpawn = 'ship_module',
        shipSystemType = 'comms_array',
        powerDraw = 8,
        category = 'colony',
    },
    ship_cargo_bay = {
        name = 'Cargo Bay', desc = 'Bulk storage for ship transport. Items stored survive transit.',
        w = 2, h = 2,
        cost = { steel = 15, components = 5 },
        entitySpawn = 'ship_module',
        shipSystemType = 'cargo_bay',
        category = 'logistics',
    },
    ship_workshop = {
        name = 'Ship Workshop', desc = 'Fabricates repair parts and hull patches in flight.',
        w = 2, h = 2,
        cost = { steel = 15, components = 10 },
        entitySpawn = 'ship_module',
        shipSystemType = 'workshop',
        powerDraw = 15,
        category = 'production',
    },
    stealth_module = {
        name = 'Stealth Module', desc = 'Reduces heat signature. Scout ships only. High power drain.',
        w = 1, h = 1,
        cost = { steel = 10, components = 15, circuit = 10 },
        entitySpawn = 'ship_module',
        shipSystemType = 'stealth_module',
        powerDraw = 30,
        category = 'defense',
    },

    ---------------------------------------------------------------------------
    -- Shipyard (ground building, endgame)
    ---------------------------------------------------------------------------
    shipyard = {
        name = 'Shipyard', desc = 'Constructs colony ships. Requires launch pad adjacent. Massive resource investment.',
        w = 5, h = 5,
        tile = Tiles.FLOOR_METAL or 3,
        cost = { steel = 100, components = 50, circuit = 30 },
        entitySpawn = 'shipyard',
        powerDraw = 100,
        category = 'colony',
    },
}
