local Tiles = require('src.world.tiles')

return {
    -- Gas/Chemical turrets
    turret_gas = {
        name = 'Gas Turret', desc = 'Sprays toxic gas cloud. Slows and poisons.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 8, components = 4, circuit = 2 },
        entitySpawn = 'turret', turretType = 'gas_turret', powerDraw = 20,
    },
    turret_acid = {
        name = 'Acid Sprayer', desc = 'Short-range corrosive spray. Melts through armor.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 6, components = 3, glass = 3 },
        entitySpawn = 'turret', turretType = 'acid_sprayer', powerDraw = 25,
    },
    turret_poison = {
        name = 'Poison Dart Turret', desc = 'Silent, long-range poison delivery. Lethal over time.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 5, components = 3, medicinal_herb = 4 },
        entitySpawn = 'turret', turretType = 'poison_turret', powerDraw = 15,
    },

    -- Laser barriers / energy fences
    laser_gate = {
        name = 'Laser Gate', desc = 'Toggled energy barrier. Blocks and burns hostiles when active.',
        w = 1, h = 1, tile = nil,
        cost = { steel = 6, components = 4, circuit = 2 },
        entitySpawn = 'laser_fence', laserType = 'laser_gate', powerDraw = 20,
    },
    laser_fence = {
        name = 'Laser Fence', desc = 'Persistent laser beam. Creatures take damage passing through.',
        w = 1, h = 1, tile = nil,
        cost = { steel = 4, components = 3, circuit = 1 },
        entitySpawn = 'laser_fence', laserType = 'laser_fence', powerDraw = 15,
    },
    laser_grid = {
        name = 'Laser Grid', desc = 'Dense laser mesh across a corridor. Near-lethal to anything walking through.',
        w = 1, h = 1, tile = nil,
        cost = { steel = 8, components = 6, circuit = 3 },
        entitySpawn = 'laser_fence', laserType = 'laser_grid', powerDraw = 30,
    },
    electrified_wall = {
        name = 'Electrified Wall', desc = 'Powered wall that shocks creatures on contact.',
        w = 1, h = 1, tile = nil,
        cost = { steel = 5, components = 2, circuit = 2 },
        entitySpawn = 'laser_fence', laserType = 'electrified_wall', powerDraw = 10,
    },
    shield_curtain = {
        name = 'Shield Curtain', desc = 'Energy curtain that blocks creatures and projectiles.',
        w = 1, h = 1, tile = nil,
        cost = { steel = 8, components = 5, circuit = 4 },
        entitySpawn = 'laser_fence', laserType = 'shield_curtain', powerDraw = 25,
    },

    -- Perimeter sensors
    motion_sensor = {
        name = 'Motion Sensor', desc = 'Detects hostiles in a wide radius. Triggers colony alert and auto-locks nearby gates.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 4, components = 3, circuit = 2 },
        entitySpawn = 'sensor', sensorRadius = 15, powerDraw = 10,
    },
    seismic_sensor = {
        name = 'Seismic Sensor', desc = 'Detects underground movement. Extended range, lower power.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 6, components = 4, circuit = 2 },
        entitySpawn = 'sensor', sensorRadius = 25, powerDraw = 8,
    },

    -- Pipe infrastructure
    small_pipe = {
        name = 'Small Pipe', desc = 'Carries fluid. Low throughput.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 2 },
        entitySpawn = 'pipe', pipeType = 'small_pipe', pipeMedium = 'fluid',
    },
    large_pipe = {
        name = 'Large Pipe', desc = 'Carries fluid. High throughput.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 5, components = 1 },
        entitySpawn = 'pipe', pipeType = 'large_pipe', pipeMedium = 'fluid',
    },
    insulated_pipe = {
        name = 'Insulated Pipe', desc = 'Carries fluid. Resists freezing.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 3, components = 1 },
        entitySpawn = 'pipe', pipeType = 'insulated_pipe', pipeMedium = 'fluid',
    },
    small_duct = {
        name = 'Small Duct', desc = 'Carries gas. Low throughput.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 1 },
        entitySpawn = 'pipe', pipeType = 'small_duct', pipeMedium = 'gas',
    },
    large_duct = {
        name = 'Large Duct', desc = 'Carries gas. High throughput.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 4, components = 1 },
        entitySpawn = 'pipe', pipeType = 'large_duct', pipeMedium = 'gas',
    },
    sealed_duct = {
        name = 'Sealed Duct', desc = 'Carries gas. Leak-proof.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 2, components = 2 },
        entitySpawn = 'pipe', pipeType = 'sealed_duct', pipeMedium = 'gas',
    },

    -- Fluid/gas storage tanks
    fluid_tank_small = {
        name = 'Small Fluid Tank', desc = 'Stores fluid. Moderate capacity.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 8 },
        entitySpawn = 'tank', tankType = 'fluid_tank_small',
    },
    fluid_tank_large = {
        name = 'Large Fluid Tank', desc = 'Stores fluid. High capacity.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 20, steel = 3 },
        entitySpawn = 'tank', tankType = 'fluid_tank_large',
    },
    gas_canister = {
        name = 'Gas Canister', desc = 'Stores compressed gas.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 6 },
        entitySpawn = 'tank', tankType = 'gas_canister',
    },
    pressurized_tank = {
        name = 'Pressurized Tank', desc = 'Stores gas under pressure. High capacity.',
        w = 1, h = 1, tile = nil,
        cost = { steel = 8, components = 3 },
        entitySpawn = 'tank', tankType = 'pressurized_tank',
    },

    -- Fluid/gas processors
    water_pump = {
        name = 'Water Pump', desc = 'Extracts water from ice. Requires power.',
        w = 1, h = 1, tile = Tiles.FLOOR_METAL,
        cost = { metal = 6, components = 2 },
        entitySpawn = 'processor', processorType = 'water_pump', powerDraw = 15,
    },
    oil_refinery = {
        name = 'Oil Refinery', desc = 'Processes crude oil into fuel. Requires power.',
        w = 1, h = 1, tile = Tiles.FLOOR_METAL,
        cost = { metal = 20, components = 5, steel = 3 },
        entitySpawn = 'processor', processorType = 'oil_refinery', powerDraw = 35,
    },
    coolant_refiner = {
        name = 'Coolant Refiner', desc = 'Produces coolant from raw materials. Requires power.',
        w = 1, h = 1, tile = Tiles.FLOOR_METAL,
        cost = { metal = 12, components = 4 },
        entitySpawn = 'processor', processorType = 'coolant_refiner', powerDraw = 20,
    },
    ichor_converter = {
        name = 'Ichor Converter', desc = 'Processes eldritch ichor into usable compounds. Requires power.',
        w = 1, h = 1, tile = Tiles.FLOOR_METAL,
        cost = { steel = 10, components = 6, circuit = 2 },
        entitySpawn = 'processor', processorType = 'ichor_converter', powerDraw = 10,
    },
    waste_processor = {
        name = 'Waste Processor', desc = 'Breaks down industrial waste. Requires power.',
        w = 1, h = 1, tile = Tiles.FLOOR_METAL,
        cost = { metal = 10, components = 3 },
        entitySpawn = 'processor', processorType = 'waste_processor', powerDraw = 12,
    },
    gas_separator = {
        name = 'Gas Separator', desc = 'Separates gas mixtures into components. Requires power.',
        w = 1, h = 1, tile = Tiles.FLOOR_METAL,
        cost = { steel = 8, components = 5, circuit = 1 },
        entitySpawn = 'processor', processorType = 'gas_separator', powerDraw = 25,
    },
    steam_boiler = {
        name = 'Steam Boiler', desc = 'Generates steam from water and heat.',
        w = 1, h = 1, tile = Tiles.FLOOR_METAL,
        cost = { metal = 15, components = 4 },
        entitySpawn = 'processor', processorType = 'steam_boiler',
    },
    fuel_generator = {
        name = 'Fuel Generator', desc = 'Burns refined fuel from pipes to produce 60W power.',
        w = 1, h = 1, tile = Tiles.FLOOR_METAL,
        cost = { steel = 6, components = 4, circuit = 1 },
        entitySpawn = 'processor', processorType = 'fuel_generator',
    },
    oil_pump = {
        name = 'Oil Pump', desc = 'Extracts crude oil from deep permafrost. Requires power.',
        w = 1, h = 1, tile = Tiles.FLOOR_METAL,
        cost = { metal = 12, components = 4, steel = 2 },
        entitySpawn = 'processor', processorType = 'oil_pump', powerDraw = 25,
    },
    ichor_extractor = {
        name = 'Ichor Extractor', desc = 'Siphons eldritch ichor from a nearby sessile node. Place within 3 tiles of a mature node.',
        w = 1, h = 1, tile = Tiles.FLOOR_METAL,
        cost = { steel = 8, components = 5, circuit = 1 },
        entitySpawn = 'processor', processorType = 'ichor_extractor', powerDraw = 20,
    },

    -- Logistics
    conveyor = {
        name = 'Conveyor Belt', desc = 'Moves items in one direction. Chain them together.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 2, components = 1 },
        entitySpawn = 'conveyor',
    },
    fast_conveyor = {
        name = 'Fast Conveyor', desc = 'Reinforced belt. Moves items at 2x speed.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 3, components = 2 },
        entitySpawn = 'conveyor', beltSpeed = 2.0,
    },
    express_conveyor = {
        name = 'Express Conveyor', desc = 'High-speed belt. Moves items at 3x speed.',
        w = 1, h = 1, tile = nil,
        cost = { steel = 2, components = 3, circuit = 1 },
        entitySpawn = 'conveyor', beltSpeed = 3.0,
    },
    splitter = {
        name = 'Belt Splitter', desc = 'Splits conveyor belt output two ways.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 3, components = 2 },
        entitySpawn = 'splitter',
    },
    fast_splitter = {
        name = 'Fast Splitter', desc = 'Splits belt output at 2x speed.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 4, components = 3 },
        entitySpawn = 'splitter', beltSpeed = 2.0,
    },
    express_splitter = {
        name = 'Express Splitter', desc = 'Splits belt output at 3x speed.',
        w = 1, h = 1, tile = nil,
        cost = { steel = 3, components = 4, circuit = 1 },
        entitySpawn = 'splitter', beltSpeed = 3.0,
    },
    basic_inserter = {
        name = 'Basic Inserter', desc = 'Moves items between belts and machines. Slow.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 3, components = 1 },
        entitySpawn = 'inserter', inserterType = 'basic_inserter',
    },
    fast_inserter = {
        name = 'Fast Inserter', desc = 'Moves items twice as fast as basic.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 4, components = 2, circuit = 1 },
        entitySpawn = 'inserter', inserterType = 'fast_inserter',
    },
    filter_inserter = {
        name = 'Filter Inserter', desc = 'Moves only specified item types.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 4, components = 3, circuit = 1 },
        entitySpawn = 'inserter', inserterType = 'filter_inserter',
    },
    stack_inserter = {
        name = 'Stack Inserter', desc = 'Transfers 4 items per cycle. High throughput.',
        w = 1, h = 1, tile = nil,
        cost = { steel = 3, components = 4, circuit = 1 },
        entitySpawn = 'inserter', inserterType = 'stack_inserter',
    },
    fast_filter_inserter = {
        name = 'Fast Filter Inserter', desc = 'Rapid filtered item transfer.',
        w = 1, h = 1, tile = nil,
        cost = { steel = 3, components = 4, circuit = 2 },
        entitySpawn = 'inserter', inserterType = 'fast_filter_inserter',
    },
    storage_chest = {
        name = 'Storage Chest', desc = 'Holds items for inserter automation. 20 slots.',
        w = 1, h = 1, tile = nil,
        cost = { wood = 10, metal = 2 },
        entitySpawn = 'stockpile',
    },
    steel_chest = {
        name = 'Steel Chest', desc = 'Reinforced storage. 40 slots.',
        w = 1, h = 1, tile = nil,
        cost = { steel = 5, metal = 3 },
        entitySpawn = 'stockpile', stockpileCapacity = 40,
    },

    -- Power grid and advanced generation
    power_conduit = {
        name = 'Power Conduit', desc = 'Wire that carries electricity between buildings.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 1 },
        entitySpawn = 'power_conduit',
    },
    battery_crude = {
        name = 'Crude Battery', desc = 'Wood-frame lead-acid cell. Cheap but leaky.',
        w = 1, h = 1, tile = nil,
        cost = { wood = 16, metal = 8 },
        entitySpawn = 'battery',
        batteryCapacity = 800,
        batteryChargeEff = 0.35,
        batterySelfDischarge = 0.005,
    },
    battery = {
        name = 'Battery', desc = 'Standard metal-cased battery. Reliable storage.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 16, components = 8 },
        entitySpawn = 'battery', batteryCapacity = 2000,
    },
    battery_large = {
        name = 'Large Battery', desc = 'High-capacity storage bank. Double the standard.',
        w = 1, h = 1, tile = nil,
        cost = { steel = 10, components = 12, circuit = 4 },
        entitySpawn = 'battery', batteryCapacity = 4000,
    },
    capacitor_bank = {
        name = 'Capacitor Bank', desc = 'Fast-charge storage. High efficiency, lower capacity.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 12, components = 10, circuit = 4 },
        entitySpawn = 'battery',
        batteryCapacity = 1000,
        batteryChargeEff = 0.95,
        batterySelfDischarge = 0.001,
    },
    thermal_battery = {
        name = 'Thermal Battery', desc = 'Stores energy as molten salt heat. Good capacity, slow charge.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 20, stone = 16, components = 6 },
        entitySpawn = 'battery',
        batteryCapacity = 3000,
        batteryChargeEff = 0.4,
        batterySelfDischarge = 0.003,
    },
    cryo_cell = {
        name = 'Cryo Cell', desc = 'Superconducting storage. Colony-scale power reserve.',
        w = 1, h = 1, tile = nil,
        cost = { steel = 100, components = 80, circuit = 40 },
        entitySpawn = 'battery',
        batteryCapacity = 30000,
        batteryChargeEff = 0.7,
        batterySelfDischarge = 0.0003,
    },
    eldritch_accumulator = {
        name = 'Eldritch Accumulator', desc = 'Ichor-based energy vessel. Enough storage to last a full winter.',
        w = 1, h = 1, tile = nil,
        cost = { steel = 80, components = 60, circuit = 30, eldritch_ichor = 50 },
        entitySpawn = 'battery',
        batteryCapacity = 50000,
        batteryChargeEff = 0.6,
        batterySelfDischarge = 0.001,
    },
    power_switch = {
        name = 'Power Switch', desc = 'Toggle to isolate parts of the power grid.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 3, components = 2 },
        entitySpawn = 'power_switch',
    },
    cryo_kinetic = {
        name = 'Cryo-Kinetic Engine', desc = 'Harvests energy from sub-zero temps. Absorbs heat, cooling the area.',
        w = 1, h = 1, tile = Tiles.FLOOR_METAL,
        cost = { metal = 15, components = 5, circuit = 2 },
        entitySpawn = 'generator', genType = 'cryo_kinetic',
        heatOutput = -20, heatTarget = -5,
        heatDanger = { radius = 1, tempOffset = -15 },
    },
    methane_digester = {
        name = 'Methane Digester', desc = 'Ferments organic matter into biogas. Modest power and heat.',
        w = 1, h = 1, tile = Tiles.FLOOR_METAL,
        cost = { metal = 10, wood = 8, components = 3 },
        entitySpawn = 'generator', genType = 'methane_digester',
        heatOutput = 20, heatTarget = 22,
    },
    plasma_arc = {
        name = 'Plasma Arc Reactor', desc = 'Extreme-output arc furnace. Burns steel. Scorching heat nearby.',
        w = 1, h = 1, tile = Tiles.FLOOR_METAL,
        cost = { steel = 20, components = 10, circuit = 5 },
        entitySpawn = 'generator', genType = 'plasma_arc',
        heatOutput = 100, heatTarget = 50,
        heatDanger = { radius = 2, tempOffset = 40 },
    },
    stirling_engine = {
        name = 'Stirling Engine', desc = 'Sealed piston engine powered by temperature differential. Slight warmth.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 10, components = 4 },
        entitySpawn = 'generator', genType = 'stirling_engine',
        heatOutput = 5, heatTarget = 16,
    },
    penrose_engine = {
        name = 'Penrose Engine', desc = 'Eldritch perpetual motion device. Runs without fuel. Nobody knows how.',
        w = 1, h = 1, tile = nil,
        cost = { steel = 15, circuit = 8, eldritch_ichor = 10 },
        entitySpawn = 'generator', genType = 'penrose_engine',
    },
    dynamo = {
        name = 'Dynamo', desc = 'Hand-cranked generator. More efficient than the basic crank.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 8, components = 3 },
        entitySpawn = 'generator', genType = 'dynamo',
    },
    peat_burner = {
        name = 'Peat Burner', desc = 'Burns peat and organic fuel. Good heat, moderate power.',
        w = 1, h = 1, tile = Tiles.FLOOR_STONE,
        cost = { stone = 10, metal = 5 },
        entitySpawn = 'generator', genType = 'peat_burner',
        heatOutput = 55, heatTarget = 30,
    },
    fusion_reactor = {
        name = 'Fusion Reactor', desc = 'Contained fusion reaction. 400W output. Meltdown risk if faulted. Hot nearby.',
        w = 1, h = 1, tile = Tiles.FLOOR_METAL,
        cost = { steel = 30, components = 15, circuit = 10 },
        entitySpawn = 'generator', genType = 'fusion_reactor',
        heatOutput = 50, heatTarget = 28,
        heatDanger = { radius = 2, tempOffset = 35 },
    },
    thermal_gen = {
        name = 'Thermal Generator', desc = 'Converts fuel into heat and power. Radiates warmth.',
        w = 1, h = 1, tile = Tiles.FLOOR_METAL,
        cost = { metal = 12, components = 3 },
        entitySpawn = 'generator', genType = 'thermal_gen',
        heatOutput = 35, heatTarget = 25,
    },
    lava_tap = {
        name = 'Lava Vent Tap', desc = '100W free power from a lava vent. No fuel cost. Dangerously hot nearby.',
        w = 1, h = 1, tile = Tiles.FLOOR_METAL,
        cost = { steel = 15, components = 8, circuit = 3 },
        entitySpawn = 'generator', genType = 'lava_tap',
        heatOutput = 60, heatTarget = 40,
        heatDanger = { radius = 2, tempOffset = 30 },
    },
}
