local Tiles = require('src.world.tiles')

return {
    -- Production machines
    sawmill = {
        name = 'Sawmill', desc = 'Processes raw wood into lumber.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_WOOD,
        cost = { wood = 15, metal = 5 },
        entitySpawn = 'machine',
        machineType = 'sawmill',
    },
    smelter = {
        name = 'Smelter', desc = 'Melts ore into metal ingots. Requires power.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_METAL,
        cost = { stone = 15, metal = 5 },
        entitySpawn = 'machine',
        machineType = 'smelter',
        powerDraw = 25,
    },
    forge = {
        name = 'Forge', desc = 'Shapes metal into steel, components, and tools. Requires power.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_METAL,
        cost = { metal = 15, components = 3 },
        entitySpawn = 'machine',
        machineType = 'forge',
        powerDraw = 30,
    },
    kitchen = {
        name = 'Kitchen', desc = 'Cooks raw food into meals.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_WOOD,
        cost = { wood = 10, metal = 3 },
        entitySpawn = 'machine',
        machineType = 'kitchen',
    },
    workbench = {
        name = 'Workbench', desc = 'General crafting station for tools, clothes, and gear.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_WOOD,
        cost = { wood = 10, metal = 5 },
        entitySpawn = 'machine',
        machineType = 'workbench',
    },
    loom = {
        name = 'Loom', desc = 'Weaves fiber and hide into cloth.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_WOOD,
        cost = { wood = 12, hide = 3 },
        entitySpawn = 'machine',
        machineType = 'loom',
    },
    tannery = {
        name = 'Tannery', desc = 'Processes raw hides into leather.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_WOOD,
        cost = { wood = 10, stone = 5 },
        entitySpawn = 'machine',
        machineType = 'tannery',
    },
    smokehouse = {
        name = 'Smokehouse', desc = 'Cures meat into jerky. Long shelf life.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_WOOD,
        cost = { wood = 15, stone = 5 },
        entitySpawn = 'machine',
        machineType = 'smokehouse',
    },
    drug_lab = {
        name = 'Drug Lab', desc = 'Synthesizes drugs and medicine. Requires power.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_METAL,
        cost = { metal = 10, components = 5 },
        entitySpawn = 'machine',
        machineType = 'drug_lab',
        powerDraw = 15,
    },
    butcher_table = {
        name = 'Butcher Table', desc = 'Butchers corpses into meat and hide.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_WOOD,
        cost = { wood = 10, metal = 3 },
        entitySpawn = 'machine',
        machineType = 'butcher_table',
    },
    surgery_table = {
        name = 'Surgery Table', desc = 'Perform surgery and install prosthetics. Requires power.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_METAL,
        cost = { metal = 10, components = 3 },
        entitySpawn = 'machine',
        machineType = 'surgery_table',
        powerDraw = 10,
    },
    refinery = {
        name = 'Refinery', desc = 'Processes raw materials into fuel. Requires power.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_METAL,
        cost = { metal = 20, components = 5 },
        entitySpawn = 'machine',
        machineType = 'refinery',
        powerDraw = 35,
    },
    melter = {
        name = 'Ice Melter', desc = 'Melts raw ice into water. Requires power.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_METAL,
        cost = { metal = 5, stone = 3 },
        entitySpawn = 'machine',
        machineType = 'melter',
        powerDraw = 5,
    },

    centrifuge = {
        name = 'Centrifuge', desc = 'Separates uranium ore into enriched and depleted uranium. Requires power.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_METAL,
        cost = { steel = 8, components = 4, circuit = 1 },
        entitySpawn = 'machine',
        machineType = 'centrifuge',
        powerDraw = 20,
    },
    refiner = {
        name = 'Refiner', desc = 'Melts ice blocks into water. Requires power.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_METAL,
        cost = { metal = 6, pipe = 3 },
        entitySpawn = 'machine',
        machineType = 'refiner',
        powerDraw = 5,
    },

    -- Advanced production machines (upgrade tiers)
    powered_sawmill = {
        name = 'Powered Sawmill', desc = 'Electric sawmill. Faster lumber processing.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_METAL,
        cost = { metal = 10, components = 3 },
        entitySpawn = 'machine',
        machineType = 'powered_sawmill',
        powerDraw = 15,
    },
    advanced_smelter = {
        name = 'Advanced Smelter', desc = 'High-capacity electric smelter. Double throughput.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_METAL,
        cost = { steel = 10, components = 5, circuit = 2 },
        entitySpawn = 'machine',
        machineType = 'advanced_smelter',
        powerDraw = 40,
    },
    precision_forge = {
        name = 'Precision Forge', desc = 'Computer-controlled forge. Faster, less waste.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_METAL,
        cost = { steel = 12, components = 6, circuit = 3 },
        entitySpawn = 'machine',
        machineType = 'precision_forge',
        powerDraw = 45,
    },
    industrial_kitchen = {
        name = 'Industrial Kitchen', desc = 'Electric kitchen with temperature control. Faster cooking.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_METAL,
        cost = { metal = 12, components = 4, circuit = 1 },
        entitySpawn = 'machine',
        machineType = 'industrial_kitchen',
        powerDraw = 20,
    },
    advanced_drug_lab = {
        name = 'Advanced Drug Lab', desc = 'Precision drug synthesis. Higher yield, faster output.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_METAL,
        cost = { steel = 8, components = 6, circuit = 3 },
        entitySpawn = 'machine',
        machineType = 'advanced_drug_lab',
        powerDraw = 25,
    },
    sterile_surgery = {
        name = 'Sterile Surgery Suite', desc = 'Clean-room surgery. Higher success rate.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_METAL,
        cost = { steel = 8, components = 5, circuit = 2 },
        entitySpawn = 'machine',
        machineType = 'sterile_surgery',
        powerDraw = 15,
    },

    -- Power generation
    solar_panel = {
        name = 'Solar Panel', desc = 'Generates power from sunlight. Weak in polar winter, dead at night.',
        w = 1, h = 1,
        tile = nil,
        cost = { metal = 8, components = 3 },
        entitySpawn = 'generator',
        genType = 'solar_panel',
    },
    tracking_solar = {
        name = 'Tracking Solar Array', desc = 'Motorised mount tracks the sun. 65W peak, better dawn/dusk output.',
        w = 1, h = 1,
        tile = nil,
        cost = { metal = 15, components = 6, circuit = 2 },
        entitySpawn = 'generator',
        genType = 'tracking_solar',
    },
    concentrated_solar = {
        name = 'Concentrated Solar', desc = 'Mirror array focuses sunlight. 100W peak output.',
        w = 1, h = 1,
        tile = nil,
        cost = { steel = 10, components = 8, circuit = 4 },
        entitySpawn = 'generator',
        genType = 'concentrated_solar',
    },
    wind_turbine = {
        name = 'Wind Turbine', desc = 'Generates power from wind. Output varies with weather.',
        w = 1, h = 1,
        tile = nil,
        cost = { metal = 12, components = 4 },
        entitySpawn = 'generator',
        genType = 'wind_turbine',
    },
    large_wind_turbine = {
        name = 'Large Wind Turbine', desc = 'Taller tower, longer blades. 90W in good wind.',
        w = 1, h = 1,
        tile = nil,
        cost = { metal = 20, components = 6, steel = 3 },
        entitySpawn = 'generator',
        genType = 'large_wind_turbine',
    },
    advanced_turbine = {
        name = 'Advanced Turbine', desc = 'Variable-pitch blades extract power in any weather. 130W.',
        w = 1, h = 1,
        tile = nil,
        cost = { steel = 12, components = 8, circuit = 3 },
        entitySpawn = 'generator',
        genType = 'advanced_turbine',
    },
    geothermal = {
        name = 'Geothermal Vent', desc = 'Taps underground heat for steady power. Radiates warmth.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_METAL,
        cost = { metal = 20, components = 5, steel = 5 },
        entitySpawn = 'generator',
        genType = 'geothermal',
        heatOutput = 45, heatTarget = 30,
    },
    gas_burner = {
        name = 'Gas Burner', desc = 'Burns gas for power and heat.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_METAL,
        cost = { metal = 8, components = 2 },
        entitySpawn = 'generator',
        genType = 'gas_burner',
        heatOutput = 50, heatTarget = 35,
        fuelRate = 0.04,
    },
    coal_burner = {
        name = 'Coal Burner', desc = 'Burns coal for power and heat.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_METAL,
        cost = { metal = 10, components = 2 },
        entitySpawn = 'generator',
        genType = 'coal_burner',
        heatOutput = 35, heatTarget = 28,
        fuelRate = 0.05,
    },
    nuclear_reactor = {
        name = 'Nuclear Reactor', desc = 'High-output power. Meltdown risk if damaged. Emits radiation — use lead walls.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_METAL,
        cost = { steel = 20, components = 10, circuit = 5 },
        entitySpawn = 'generator',
        genType = 'nuclear_reactor',
        heatOutput = 35, heatTarget = 25,
        heatDanger = { radius = 2, tempOffset = 25 },
    },
    chemical_burner = {
        name = 'Chemical Burner', desc = 'Burns chemicals for power and moderate heat.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_METAL,
        cost = { metal = 10, components = 3 },
        entitySpawn = 'generator',
        genType = 'chemical_burner',
        heatOutput = 30, heatTarget = 25,
        fuelRate = 0.03,
    },
    fire_pit = {
        name = 'Fire Pit', desc = 'Burns anything organic. Good heat, smoky.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_STONE,
        cost = { stone = 8, wood = 5 },
        heatOutput = 60, heatTarget = 30,
        fuelRate = 0.08,
        lightPreset = 'campfire',
    },
    deep_fire_pit = {
        name = 'Deep Fire Pit', desc = 'Contained fire pit. Less smoke, less fire spread.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_STONE,
        cost = { stone = 15, metal = 3 },
        heatOutput = 70, heatTarget = 32,
        fuelRate = 0.07,
        lightPreset = 'campfire',
    },
    bio_reactor = {
        name = 'Bio Reactor', desc = 'Generates power from organic waste. Mild warmth.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_METAL,
        cost = { metal = 12, components = 4 },
        entitySpawn = 'generator',
        genType = 'bio_reactor',
        heatOutput = 10, heatTarget = 18,
    },
    mini_reactor = {
        name = 'Mini Reactor', desc = 'Compact nuclear power. Mild radiation. Lead shielding recommended.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_METAL,
        cost = { steel = 10, components = 5, circuit = 2 },
        entitySpawn = 'generator',
        genType = 'mini_reactor',
        heatOutput = 20, heatTarget = 22,
        heatDanger = { radius = 1, tempOffset = 15 },
    },
    steam_turbine = {
        name = 'Steam Turbine', desc = 'Converts steam pressure into electricity. Vents warm exhaust.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_METAL,
        cost = { metal = 15, components = 4 },
        entitySpawn = 'generator',
        genType = 'steam_turbine',
        heatOutput = 15, heatTarget = 20,
    },
    hand_crank = {
        name = 'Hand Crank', desc = 'Manual generator. A colonist turns it by hand.',
        w = 1, h = 1,
        tile = nil,
        cost = { wood = 10, metal = 3 },
        entitySpawn = 'generator',
        genType = 'hand_crank',
    },
    treadmill = {
        name = 'Treadmill Generator', desc = 'Colonist-powered generator. Slow but reliable.',
        w = 1, h = 1,
        tile = nil,
        cost = { wood = 15, metal = 5 },
        entitySpawn = 'generator',
        genType = 'treadmill',
    },
    chain_gang_wheel = {
        name = 'Chain Gang Wheel', desc = 'Forced-labor generator. High output, costs morale.',
        w = 1, h = 1,
        tile = nil,
        cost = { wood = 20, metal = 10 },
        entitySpawn = 'generator',
        genType = 'chain_gang_wheel',
    },
    waste_incinerator = {
        name = 'Waste Incinerator', desc = 'Burns waste for power and heat.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_METAL,
        cost = { metal = 10, stone = 8 },
        entitySpawn = 'generator',
        genType = 'waste_incinerator',
        heatOutput = 45, heatTarget = 30,
    },
    hydrogen_cell = {
        name = 'Hydrogen Fuel Cell', desc = 'Clean power from hydrogen. Late-game tech.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_METAL,
        cost = { steel = 8, components = 5, circuit = 2 },
        entitySpawn = 'generator',
        genType = 'hydrogen_cell',
    },
    lightning_rod = {
        name = 'Lightning Rod', desc = 'Captures storm energy. Output depends on weather.',
        w = 1, h = 1,
        tile = nil,
        cost = { metal = 15, components = 3 },
        entitySpawn = 'generator',
        genType = 'lightning_rod',
    },
    thermopile = {
        name = 'Thermopile', desc = 'Converts temperature difference into power.',
        w = 1, h = 1,
        tile = nil,
        cost = { metal = 8, components = 3 },
        entitySpawn = 'generator',
        genType = 'thermopile',
    },
    ichor_burner = {
        name = 'Ichor Burner', desc = 'Burns eldritch ichor for power. Dirty fumes.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_METAL,
        cost = { metal = 12, components = 3, stone = 5 },
        entitySpawn = 'generator',
        genType = 'ichor_burner',
        heatOutput = 50, heatTarget = 35,
        fuelRate = 0.035,
    },

    -- Automated mining drills (Factorio-style, no operator needed)
    burner_drill = {
        name = 'Burner Mining Drill', desc = 'Burns fuel to extract ore. No power needed. Slow but cheap.',
        w = 1, h = 1,
        tile = nil,
        cost = { stone = 10, metal = 5 },
        entitySpawn = 'miner',
        minerType = 'burner_drill',
    },
    electric_drill = {
        name = 'Electric Mining Drill', desc = 'Automated ore extraction. Requires 30W power.',
        w = 1, h = 1,
        tile = nil,
        cost = { metal = 12, components = 4 },
        entitySpawn = 'miner',
        minerType = 'electric_drill',
        powerDraw = 30,
    },
    advanced_drill = {
        name = 'Advanced Mining Drill', desc = 'High-speed automated extraction. 60W. Better yield.',
        w = 1, h = 1,
        tile = nil,
        cost = { steel = 8, components = 6, circuit = 2 },
        entitySpawn = 'miner',
        minerType = 'advanced_drill',
        powerDraw = 60,
    },
    bore_drill = {
        name = 'Bore Drill', desc = 'Drills down through z-levels creating stair connections. Breaks after several layers.',
        w = 1, h = 1,
        tile = nil,
        cost = { steel = 12, components = 8, circuit = 3 },
        entitySpawn = 'miner',
        minerType = 'bore_drill',
        powerDraw = 80,
    },
}
