local Tiles = require('src.world.tiles')

return {
    -- Turrets
    turret_ballista = {
        name = 'Ballista', desc = 'Fires heavy bolts. Slow, no power needed.',
        w = 1, h = 1, tile = nil,
        cost = { wood = 20, metal = 5 },
        entitySpawn = 'turret', turretType = 'ballista',
    },
    turret_crossbow = {
        name = 'Auto-Crossbow', desc = 'Rapid-fire bolts. No power needed.',
        w = 1, h = 1, tile = nil,
        cost = { wood = 15, metal = 3 },
        entitySpawn = 'turret', turretType = 'crossbow_turret',
    },
    turret_gun = {
        name = 'Gun Turret', desc = 'Standard ballistic turret. Requires power.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 15, components = 5 },
        entitySpawn = 'turret', turretType = 'gun', powerDraw = 10,
    },
    turret_minigun = {
        name = 'Minigun Turret', desc = 'High rate of fire. Heavy power draw.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 20, components = 8 },
        entitySpawn = 'turret', turretType = 'minigun', powerDraw = 15,
    },
    turret_shotgun = {
        name = 'Shotgun Turret', desc = 'Short range, wide spread. Requires power.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 12, components = 4 },
        entitySpawn = 'turret', turretType = 'shotgun_turret', powerDraw = 10,
    },
    mortar = {
        name = 'Mortar', desc = 'Long range explosive shells. Manual reload.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 20, components = 5 },
        entitySpawn = 'turret', turretType = 'mortar',
    },
    turret_rocket = {
        name = 'Rocket Turret', desc = 'Fires explosive rockets. High damage, slow reload.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 25, components = 8, steel = 5 },
        entitySpawn = 'turret', turretType = 'rocket_turret',
    },
    turret_laser = {
        name = 'Laser Turret', desc = 'Focused energy beam. High power draw.',
        w = 1, h = 1, tile = nil,
        cost = { steel = 8, components = 5, circuit = 2 },
        entitySpawn = 'turret', turretType = 'laser', powerDraw = 30,
    },
    turret_tesla = {
        name = 'Tesla Coil', desc = 'Chain lightning. Hits multiple targets. Heavy power draw.',
        w = 1, h = 1, tile = nil,
        cost = { steel = 10, components = 5, circuit = 3 },
        entitySpawn = 'turret', turretType = 'tesla', powerDraw = 40,
    },
    turret_flamethrower = {
        name = 'Flamethrower Turret', desc = 'Area denial. Sets targets on fire. Requires power.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 15, components = 4 },
        entitySpawn = 'turret', turretType = 'flamethrower', powerDraw = 20,
    },
    turret_cryo = {
        name = 'Cryo Turret', desc = 'Slows targets with freezing spray. Requires power.',
        w = 1, h = 1, tile = nil,
        cost = { steel = 6, components = 4, circuit = 1 },
        entitySpawn = 'turret', turretType = 'cryo_turret', powerDraw = 25,
    },
    turret_heat_drain = {
        name = 'Heat-Drain Turret', desc = 'Drains thermal energy from nearby enemies. Deals cold damage over time.',
        w = 1, h = 1, tile = nil,
        cost = { steel = 8, thermalCores = 2, components = 5, circuit = 2 },
        entitySpawn = 'turret', turretType = 'heat_drain', powerDraw = 30,
    },
    turret_railgun = {
        name = 'Railgun Emplacement', desc = 'Electromagnetic slug. Extreme range and damage.',
        w = 1, h = 1, tile = nil,
        cost = { steel = 15, components = 8, circuit = 4 },
        entitySpawn = 'turret', turretType = 'railgun', powerDraw = 60,
    },
    turret_emp = {
        name = 'EMP Cannon', desc = 'Disables mechanical targets. Requires power.',
        w = 1, h = 1, tile = nil,
        cost = { steel = 10, components = 6, circuit = 3 },
        entitySpawn = 'turret', turretType = 'emp_cannon', powerDraw = 35,
    },
    turret_sniper = {
        name = 'Sniper Nest', desc = 'Long range, high accuracy. Manned position.',
        w = 1, h = 1, tile = nil,
        cost = { wood = 15, metal = 10, components = 3 },
        entitySpawn = 'turret', turretType = 'sniper_nest',
    },
    turret_autocannon = {
        name = 'Autocannon', desc = 'Rapid ballistic fire. Requires power.',
        w = 1, h = 1, tile = nil,
        cost = { steel = 8, components = 6, circuit = 1 },
        entitySpawn = 'turret', turretType = 'autocannon', powerDraw = 25,
    },
    turret_grenade_launcher = {
        name = 'Grenade Launcher Turret', desc = 'Lobs explosive grenades. Area damage.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 15, components = 5 },
        entitySpawn = 'turret', turretType = 'grenade_launcher',
    },
    turret_heavy_mg = {
        name = 'Heavy MG Nest', desc = 'Sustained heavy fire. Manned position.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 18, components = 6 },
        entitySpawn = 'turret', turretType = 'heavy_mg',
    },
    turret_napalm_sprayer = {
        name = 'Napalm Sprayer', desc = 'Short range incendiary. Sets everything on fire. Uses napalm fuel.',
        w = 1, h = 1, tile = nil,
        cost = { steel = 8, components = 4, pipe = 3 },
        entitySpawn = 'turret', turretType = 'napalm_sprayer', powerDraw = 25,
    },
    turret_foam_nozzle = {
        name = 'Foam Nozzle', desc = 'Fire suppression turret. Extinguishes fires in its area. Uses foam canisters.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 10, components = 3, pipe = 2 },
        entitySpawn = 'turret', turretType = 'foam_nozzle', powerDraw = 15,
    },
    rocket_pod = {
        name = 'Rocket Pod', desc = 'Basic unguided rocket launcher. Short range, moderate area.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 15, components = 5 },
        entitySpawn = 'turret', turretType = 'rocket_turret',
    },
    missile_battery = {
        name = 'Missile Battery', desc = 'Guided missile launcher. Long range, high damage. Uses missile ammo.',
        w = 2, h = 2, tile = Tiles.FLOOR_METAL,
        cost = { steel = 15, components = 10, circuit = 3 },
        entitySpawn = 'turret', turretType = 'missile_launcher', powerDraw = 50,
    },
    sam_launcher = {
        name = 'SAM Launcher', desc = 'Surface-to-air missile launcher. Targets aerial threats with guided rockets.',
        w = 2, h = 2, tile = Tiles.FLOOR_METAL,
        cost = { steel = 12, components = 8, circuit = 2 },
        entitySpawn = 'turret', turretType = 'sam_launcher', powerDraw = 40,
    },
    missile_silo = {
        name = 'Missile Silo', desc = 'Endgame launch facility. Extreme range, high accuracy. Houses the missile foundry.',
        w = 3, h = 3, tile = Tiles.FLOOR_METAL,
        cost = { steel = 30, components = 20, circuit = 8, cut_stone = 20 },
        entitySpawn = 'machine', machineType = 'missile_foundry', powerDraw = 50,
    },

    -- Traps
    spike_trap = {
        name = 'Spike Trap', desc = 'Metal spikes. Damages and rearms.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 3, wood = 2 },
        entitySpawn = 'trap', trapType = 'spike',
    },
    deadfall_trap = {
        name = 'Deadfall Trap', desc = 'Drops heavy rocks. High damage, slow rearm.',
        w = 1, h = 1, tile = nil,
        cost = { wood = 8, stone = 5 },
        entitySpawn = 'trap', trapType = 'deadfall',
    },
    pit_trap = {
        name = 'Pit Trap', desc = 'Hidden hole. Immobilizes targets.',
        w = 1, h = 1, tile = nil,
        cost = { wood = 5 },
        entitySpawn = 'trap', trapType = 'pit',
    },
    snare_trap = {
        name = 'Snare Trap', desc = 'Rope snare. Holds small creatures.',
        w = 1, h = 1, tile = nil,
        cost = { wood = 3, hide = 1 },
        entitySpawn = 'trap', trapType = 'snare',
    },
    razor_wire = {
        name = 'Razor Wire', desc = 'Slows and bleeds anything that crosses.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 4 },
        entitySpawn = 'trap', trapType = 'razor_wire',
    },
    bear_trap = {
        name = 'Bear Trap', desc = 'Steel jaws. Immobilizes and damages.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 6 },
        entitySpawn = 'trap', trapType = 'bear_trap',
    },
    spring_blade = {
        name = 'Spring Blade', desc = 'Concealed blade. High damage, fast rearm.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 8, components = 1 },
        entitySpawn = 'trap', trapType = 'spring_blade',
    },
    incendiary_trap = {
        name = 'Incendiary Trap', desc = 'Burns on trigger. Sets the area on fire.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 3, fuel = 5 },
        entitySpawn = 'trap', trapType = 'incendiary',
    },
    emp_mine = {
        name = 'EMP Mine', desc = 'Electromagnetic burst. Disables nearby machinery.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 5, components = 3, circuit = 1 },
        entitySpawn = 'trap', trapType = 'emp_trap',
    },
    acid_trap = {
        name = 'Acid Trap', desc = 'Corrosive splash. Damage over time.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 4, components = 2 },
        entitySpawn = 'trap', trapType = 'acid_trap',
    },
    cryo_mine = {
        name = 'Cryo Mine', desc = 'Flash-freezes the trigger area.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 5, components = 2 },
        entitySpawn = 'trap', trapType = 'cryo_mine',
    },
    frag_mine = {
        name = 'Frag Mine', desc = 'Explosive shrapnel. Area damage.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 6, components = 2 },
        entitySpawn = 'trap', trapType = 'frag_mine',
    },
    gas_trap = {
        name = 'Poison Gas Trap', desc = 'Releases toxic gas on trigger.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 4, components = 3 },
        entitySpawn = 'trap', trapType = 'gas_trap',
    },
    caltrops_trap = {
        name = 'Caltrops', desc = 'Scattered spikes. Slows foot traffic.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 2 },
        entitySpawn = 'trap', trapType = 'caltrops',
    },
    tripwire_alarm = {
        name = 'Tripwire Alarm', desc = 'Alerts the colony when triggered. No damage.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 1, wood = 2 },
        entitySpawn = 'trap', trapType = 'tripwire_alarm',
    },
    punji_pit_trap = {
        name = 'Punji Pit', desc = 'Spiked pit. Damages and immobilizes.',
        w = 1, h = 1, tile = nil,
        cost = { wood = 8, metal = 3 },
        entitySpawn = 'trap', trapType = 'punji_pit',
    },
    tripwire_ied_trap = {
        name = 'Tripwire IED', desc = 'Improvised explosive on a tripwire.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 5, fuel = 3 },
        entitySpawn = 'trap', trapType = 'tripwire_ied',
    },
    claymore_trap = {
        name = 'Claymore Mine', desc = 'Directional explosive. Heavy damage in a cone.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 8, components = 2 },
        entitySpawn = 'trap', trapType = 'claymore',
    },
    fire_trap = {
        name = 'Fire Pit Trap', desc = 'Burns targets that step over it.',
        w = 1, h = 1, tile = nil,
        cost = { wood = 5, fuel = 3 },
        entitySpawn = 'trap', trapType = 'fire_pit',
    },
    napalm_mine_trap = {
        name = 'Napalm Mine', desc = 'Sticky fire explosion. Severe burns.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 6, components = 3, fuel = 5 },
        entitySpawn = 'trap', trapType = 'napalm_mine',
    },
    foam_trap = {
        name = 'Foam Trap', desc = 'Coats the area in fire-retardant foam when triggered.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 3, raw_ice = 4 },
        entitySpawn = 'trap', trapType = 'foam_trap',
    },
    napalm_tripwire_trap = {
        name = 'Napalm Tripwire', desc = 'Tripwire-triggered napalm burst. Wide fire spread.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 4, fuel = 4, cloth = 1 },
        entitySpawn = 'trap', trapType = 'napalm_tripwire',
    },
    emp_floor_mine = {
        name = 'EMP Floor Mine', desc = 'Concealed EMP pulse. Stuns creatures and disables power.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 5, components = 3, circuit = 1 },
        entitySpawn = 'trap', trapType = 'emp_floor_mine',
    },
    barbed_fence_trap = {
        name = 'Barbed Fence', desc = 'Durable wire fence. Slows and bleeds repeatedly.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 5 },
        entitySpawn = 'trap', trapType = 'barbed_fence',
    },
    directional_mine_trap = {
        name = 'Directional Mine', desc = '120-degree blast cone. Face toward the threat.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 8, components = 2, charcoal = 3 },
        entitySpawn = 'trap', trapType = 'directional_mine',
    },
    bait_lure_trap = {
        name = 'Bait Lure', desc = 'Attracts hostile creatures. Pair with traps or killzones.',
        w = 1, h = 1, tile = nil,
        cost = { raw_meat = 5, hide = 2 },
        entitySpawn = 'trap', trapType = 'bait_lure',
    },
    pressure_plate_trap = {
        name = 'Pressure Plate', desc = 'Triggers nearby placed explosives when stepped on.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 4, components = 1 },
        entitySpawn = 'trap', trapType = 'pressure_plate',
    },
    chain_mine_trap = {
        name = 'Chain Mine', desc = 'Linked mine. When one detonates, nearby chain mines follow.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 5, charcoal = 3, components = 1 },
        entitySpawn = 'trap', trapType = 'chain_mine',
    },
    bio_mine_trap = {
        name = 'Bio Mine', desc = 'Disperses a pathogen cloud when triggered.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 4, glass = 2, medicinal_herb = 3 },
        entitySpawn = 'trap', trapType = 'bio_mine',
    },
    concussion_mine_trap = {
        name = 'Concussion Mine', desc = 'Massive blast. Destroys terrain and stuns in a wide area.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 8, charcoal = 6, components = 3 },
        entitySpawn = 'trap', trapType = 'concussion_mine',
    },
    thermobaric_trap_building = {
        name = 'Thermobaric Trap', desc = 'Consumes room oxygen on detonation. Suffocates survivors.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 6, fuel = 5, components = 3 },
        entitySpawn = 'trap', trapType = 'thermobaric_trap',
    },
    sinkhole_charge_trap = {
        name = 'Sinkhole Charge', desc = 'Collapses the floor. Drops creatures to the depth below.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 10, charcoal = 8, components = 5 },
        entitySpawn = 'trap', trapType = 'sinkhole_charge',
    },
    nuclear_mine_trap = {
        name = 'Nuclear Mine', desc = 'Nuclear detonation on proximity trigger. Last resort.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 8, components = 6, nuclear_core = 1 },
        entitySpawn = 'trap', trapType = 'nuclear_mine',
    },

    -- Cover and fortifications
    sandbag = {
        name = 'Sandbag', desc = '40% cover. Cheap and quick to place.',
        w = 1, h = 1, tile = nil,
        cost = { stone = 3 },
        entitySpawn = 'cover', coverValue = 0.4,
    },
    barricade = {
        name = 'Metal Barricade', desc = '60% cover. Sturdier than sandbags.',
        w = 1, h = 1, tile = nil,
        cost = { metal = 5 },
        entitySpawn = 'cover', coverValue = 0.6,
    },
    steel_barrier = {
        name = 'Steel Barrier', desc = '75% cover. Heavy duty protection.',
        w = 1, h = 1, tile = nil,
        cost = { steel = 4 },
        entitySpawn = 'cover', coverValue = 0.75,
    },
    bunker = {
        name = 'Bunker', desc = '85% cover. Best protection available.',
        w = 1, h = 1, tile = nil,
        cost = { steel = 8, stone = 10 },
        entitySpawn = 'cover', coverValue = 0.85,
    },
    watchtower = {
        name = 'Watchtower', desc = 'Elevated position. Extended sight range.',
        w = 1, h = 1, tile = nil,
        cost = { wood = 15, metal = 5 },
        entitySpawn = 'watchtower', sightRadius = 25,
    },
    shield_generator = {
        name = 'Shield Generator', desc = 'Energy barrier that absorbs incoming damage. Heavy power draw.',
        w = 1, h = 1, tile = nil,
        cost = { steel = 10, components = 8, circuit = 4 },
        entitySpawn = 'shield', powerDraw = 50,
    },
}
