local Tiles = require('src.world.tiles')

return {
    wall_wood = {
        name = 'Wood Wall', desc = 'Basic wall. Blocks movement, retains some heat.',
        w = 1, h = 1,
        tile = Tiles.WALL_WOOD,
        cost = { wood = 5 },
    },
    wall_stone = {
        name = 'Stone Wall', desc = 'Sturdy wall. Better insulation than wood.',
        w = 1, h = 1,
        tile = Tiles.WALL_STONE,
        cost = { wood = 1, stone = 5 },
    },
    floor_wood = {
        name = 'Wood Floor', desc = 'Simple wood flooring. Makes a room when enclosed by walls.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_WOOD,
        cost = { wood = 2 },
    },
    floor_stone = {
        name = 'Stone Floor', desc = 'Durable stone flooring.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_STONE,
        cost = { stone = 3 },
    },
    door = {
        name = 'Door', desc = 'Allows passage. Colonists open and close it automatically.',
        w = 1, h = 1,
        tile = Tiles.DOOR,
        cost = { wood = 4 },
    },
    campfire = {
        name = 'Campfire', desc = 'Burns wood for warmth. Low output, no power needed.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_STONE,
        cost = { wood = 8 },
        heatOutput = 40,
        heatTarget = 25,
        fuelRate = 0.05,
        lightPreset = 'campfire',
    },
    heater = {
        name = 'Thermal Heater', desc = 'Electric heater. Adjustable target temperature.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_METAL,
        cost = { metal = 10, components = 2 },
        heatOutput = 80,
        heatTarget = 21,
        heatControllable = true,
        fuelRate = 0.02,
        lightRadius = 5, lightIntensity = 0.7,
    },
    radiator = {
        name = 'Industrial Radiator', desc = 'High-power heater. Warms large rooms fast. Hot to the touch.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_METAL,
        cost = { steel = 6, components = 3, circuit = 1 },
        heatOutput = 140,
        heatTarget = 25,
        heatControllable = true,
        heatDanger = { radius = 1, tempOffset = 25 },
        fuelRate = 0.01,
        powerDraw = 30,
    },
    cooler = {
        name = 'Cooler', desc = 'Removes heat from a room. Adjustable target. Useful for food storage.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_METAL,
        cost = { metal = 10, components = 3 },
        heatOutput = -60,
        heatTarget = 2,
        heatControllable = true,
        heatDanger = { radius = 1, tempOffset = -10 },
        powerDraw = 20,
    },
    cryogenic_cooler = {
        name = 'Cryogenic Cooler', desc = 'Extreme cooling. Freezing cold near the unit.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_METAL,
        cost = { steel = 8, components = 5, circuit = 2 },
        heatOutput = -120,
        heatTarget = -20,
        heatControllable = true,
        heatDanger = { radius = 1, tempOffset = -30 },
        powerDraw = 40,
    },

    -- Lighting buildings
    torch = {
        name = 'Torch', desc = 'Cheap standing light. Burns slowly, reveals nearby area.',
        w = 1, h = 1,
        tile = nil,
        cost = { wood = 2 },
        lightPreset = 'torch',
        entitySpawn = 'light_source',
        sightRadius = 6,
    },
    standing_lamp = {
        name = 'Standing Lamp', desc = 'Bright electric lamp. Illuminates a large area.',
        w = 1, h = 1,
        tile = nil,
        cost = { metal = 5, components = 2 },
        lightPreset = 'lamp',
        entitySpawn = 'light_source',
        powerDraw = 5,
        sightRadius = 8,
    },

    -- Ventilation buildings
    air_intake = {
        name = 'Air Intake', desc = 'Pulls outside air into a room.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_METAL,
        cost = { metal = 5, components = 1 },
        ventType = 'air_intake',
    },
    air_exhaust = {
        name = 'Air Exhaust', desc = 'Vents room air outside. Reduces CO2.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_METAL,
        cost = { metal = 5, components = 1 },
        ventType = 'air_exhaust',
    },
    air_purifier = {
        name = 'Air Purifier', desc = 'Filters CO2 from room air. Requires power.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_METAL,
        cost = { metal = 8, components = 3 },
        ventType = 'air_purifier',
        powerDraw = 15,
    },
    wall_vent = {
        name = 'Wall Vent', desc = 'Passive vent. Slowly equalizes air between adjacent rooms or with outside.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_METAL,
        cost = { metal = 3 },
        ventType = 'wall_vent',
    },
    circulation_fan = {
        name = 'Circulation Fan', desc = 'Powered fan. Fast air equalization between rooms or with outdoors. 10W.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_METAL,
        cost = { metal = 6, components = 2 },
        ventType = 'circulation_fan',
        powerDraw = 10,
    },
    bed = {
        name = 'Bed', desc = 'Rest spot for one colonist.',
        w = 1, h = 1,
        tile = nil,
        cost = { wood = 8 },
        entitySpawn = 'bed',
    },
    comfort_bed = {
        name = 'Comfort Bed', desc = 'Padded bed. Faster rest, small morale boost.',
        w = 1, h = 1,
        tile = nil,
        cost = { wood = 10, cloth = 3 },
        entitySpawn = 'bed',
        bedQuality = 'comfort',
    },
    hospital_bed = {
        name = 'Hospital Bed', desc = 'Sterile medical bed. Boosts healing speed and surgery success.',
        w = 1, h = 1,
        tile = nil,
        cost = { metal = 8, cloth = 2, components = 2 },
        entitySpawn = 'bed',
        bedQuality = 'hospital',
    },
    memorial = {
        name = 'Memorial', desc = 'Stone marker for the dead. Boosts nearby morale.',
        w = 1, h = 1,
        tile = nil,
        cost = { stone = 5 },
        entitySpawn = 'memorial',
    },

    -- Insulated variants
    wall_insulated = {
        name = 'Insulated Wall', desc = 'Metal wall with insulation layer. Best heat retention.',
        w = 1, h = 1,
        tile = Tiles.WALL_INSULATED,
        cost = { metal = 4, components = 1 },
    },
    floor_insulated = {
        name = 'Insulated Floor', desc = 'Metal floor with insulation. Minimizes heat loss.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_INSULATED,
        cost = { metal = 2, components = 1 },
    },
    door_sealed = {
        name = 'Sealed Door', desc = 'Airtight door. Prevents heat and atmosphere leaks.',
        w = 1, h = 1,
        tile = Tiles.DOOR_SEALED,
        cost = { metal = 6, components = 2 },
    },

    -- Lead-lined (radiation shielding for nuclear rooms)
    wall_lead = {
        name = 'Lead Wall', desc = 'Dense lead-lined wall. Blocks radiation from nuclear sources.',
        w = 1, h = 1,
        tile = Tiles.WALL_LEAD,
        cost = { lead = 5, metal = 2 },
    },
    door_lead = {
        name = 'Lead Door', desc = 'Lead-lined door. Shields adjacent rooms from radiation.',
        w = 1, h = 1,
        tile = Tiles.DOOR_LEAD,
        cost = { lead = 4, metal = 2 },
    },

    -- Colony growth buildings
    cloning_vat = {
        name = 'Cloning Vat', desc = 'Grows a new colonist from biomass. Slow and expensive.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_METAL,
        cost = { metal = 15, components = 5 },
        entitySpawn = 'cloning_vat',
        powerDraw = 30,
    },
    radio_beacon = {
        name = 'Radio Beacon', desc = 'Broadcasts a signal to attract wanderers. Also attracts attention.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_METAL,
        cost = { metal = 10, components = 3 },
        entitySpawn = 'radio_beacon',
        powerDraw = 15,
        sightRadius = 40,
    },
    sos_beacon = {
        name = 'SOS Beacon',
        desc = 'Emergency distress signal. When active and powered, fires automatically if all colonists are downed. Calls 2-3 emergency reinforcements. Burns out after one use.',
        w = 2, h = 2,
        tile = Tiles.FLOOR_METAL,
        cost = { metal = 25, components = 10, circuit = 5 },
        entitySpawn = 'sos_beacon',
        powerDraw = 15,
        category = 'colony',
    },
    data_terminal = {
        name = 'Data Recovery Terminal',
        desc = 'Processes data discs recovered from fallen colonies. Restores lost research. Requires a colonist with intellectual skill to operate.',
        w = 2, h = 2,
        tile = Tiles.FLOOR_METAL,
        cost = { metal = 20, components = 8, circuit = 3 },
        entitySpawn = 'data_terminal',
        powerDraw = 20,
        category = 'production',
    },

    -- Endgame buildings
    transmission_array = {
        name = 'Transmission Array',
        desc = 'High-power signal array. Charges over 3 days, declares the colony viable to Mammona, and triggers a final assault.',
        w = 2, h = 2,
        tile = Tiles.FLOOR_METAL,
        cost = { metal = 80, components = 20, steel = 40, circuit = 10 },
        entitySpawn = 'endgame',
        endgameType = 'transmission_array',
        powerDraw = 100,
    },
    launch_pad = {
        name = 'Launch Pad',
        desc = 'Orbital shuttle pad. Once charged, it launches whoever is left into orbit. There is no coming back.',
        w = 3, h = 3,
        tile = Tiles.FLOOR_METAL,
        cost = { metal = 120, components = 30, steel = 60, fuel = 50 },
        entitySpawn = 'endgame',
        endgameType = 'launch_pad',
        powerDraw = 80,
    },
    sealing_apparatus = {
        name = 'Sealing Apparatus',
        desc = 'Precursor containment device. Reconstructed from ruin data. Forces Erebus back into dormancy.',
        w = 2, h = 2,
        tile = Tiles.FLOOR_METAL,
        cost = { metal = 60, components = 25, thermalCores = 20 },
        entitySpawn = 'endgame',
        endgameType = 'sealing_apparatus',
        powerDraw = 60,
    },
    extraction_beacon = {
        name = 'Extraction Beacon',
        desc = 'Calls Mammona\'s extraction fleet once the deep threat is broken. A corporate ending, not a rescue.',
        w = 2, h = 2,
        tile = Tiles.FLOOR_METAL,
        cost = { steel = 80, components = 40, circuit = 20, thermalCores = 30 },
        entitySpawn = 'endgame',
        endgameType = 'extraction_beacon',
        powerDraw = 100,
    },

    -- Steam hub
    steam_hub = {
        name = 'Steam Hub', desc = 'Radiates heat to nearby tiles. Requires power.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_METAL,
        cost = { metal = 8, components = 3 },
        entitySpawn = 'steam_hub',
        powerDraw = 20,
    },

    -- Agriculture
    greenhouse = {
        name = 'Greenhouse', desc = 'Heated growing space for farm plots.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_WOOD,
        cost = { wood = 10, metal = 5, components = 2 },
        heatOutput = 15,
        heatTarget = 18,
        fuelRate = 0.01,
        farmTier = 'greenhouse',
    },
    farm_plot = {
        name = 'Farm Plot', desc = 'Soil bed for crops. Must be in a heated room.',
        w = 1, h = 1,
        tile = nil,
        cost = { wood = 3 },
        entitySpawn = 'farm_plot',
        farmTier = 'outdoor',
    },
    hydroponic_basin = {
        name = 'Hydroponic Basin', desc = 'Nutrient-solution growing vat for exotic crops.',
        w = 1, h = 1,
        tile = nil,
        cost = { metal = 8, components = 4, circuit = 2 },
        entitySpawn = 'farm_plot',
        farmTier = 'hydroponic',
        powerDraw = 20,
    },
    sun_lamp = {
        name = 'Sun Lamp', desc = 'Powerful grow light. Keeps crops growing through polar night.',
        w = 1, h = 1,
        tile = Tiles.FLOOR_METAL,
        cost = { metal = 10, components = 5, circuit = 2 },
        lightPreset = nil,
        lightRadius = 7,
        lightIntensity = 1.0,
        powerDraw = 50,
    },
}
